### ISSUE TITLE
IPV6 prefixlen=10 ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [paulusmack/ppp#121]
In pppd/sys-linux.c, prefixlen is hardcoded to 10 for IPV6 ppp links. Even the route added
has rtmsg_dst_len = 10
I don't understand where this comes from/why ?

To me prefixlen should be a /128 (host address), even for the route.

**Comment by nihilus** [comment]
Because of link-local addresses. You won't get an actual routable IPv6 over the ipv6 control protocol. That's up to RA / DHCPv6 / sysadmin to provide.

**Comment by joakim-tjernlund** [comment]
My link local address for Ethernet is 64, why is ppp different?
I don't need a rotatable address for my uses case, unnumbered ppp

**Comment by nihilus** [comment]
Nope, it's not. If it is there is a bug in your ipv6 stack. The link-local scope is fe80::/10. And defined as such a link-local address should have the /10 prefix.

**Comment by joakim-tjernlund** [comment]
```
ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.210.71.11  netmask 255.255.254.0  broadcast 10.210.71.255
        inet6 2a02:1420:1:70:a75e:2266:fe9a:7c7b  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::2dec:5cde:6fcf:2501  prefixlen 64  scopeid 0x20<link>
        ether 48:0f:cf:5d:18:89  txqueuelen 1000  (Ethernet)
```
This is how Linux assigns my fe80:: address and its /64 . You think Linux is broken?
/10 defines the whole range form LL addresses, why would I use the whole range for one LL
address?

**Comment by Neustradamus** [comment]
@paulusmack: Any news about this problem?

**Comment by pali** [comment]
> In pppd/sys-linux.c, prefixlen is hardcoded to 10 for IPV6 ppp links. Even the route added has rtmsg_dst_len = 10
> I don't understand where this comes from/why ?

It comes from [RFC 4291 _IP Version 6 Addressing Architecture_, section 2.4. _Address Type Identification_](https://tools.ietf.org/html/rfc4291#section-2.4).
IPv6 _Link-Local unicast_ address type has assigned prefix FE80::/10.

> My link local address for Ethernet is 64, why is ppp different?

In section [2.5.6. _Link-Local IPv6 Unicast Addresses_](https://tools.ietf.org/html/rfc4291#section-2.5.6) can be seen that next 54 bits (after leading 10 bits) must be zeros. So effectively first 10+54=64 bits are fixed for Link-Local IPv6 addresses. Therefore Linux kernel assigns for ethernet interfaces prefix /64.

Probably authors of IPv6 standard had in mind that Link-Local addresses could be extended in future for other transport layers by using non-zeros in that second 54bit part.

So, Link-Local addresses are designed to be used for addressing on a single link and therefore should use /64 prefix. There is allocated FE80::/10 for all Link-Local addresses, which means that there are 2⁵⁴ prefixes of size /64 for single link and just only one /64 prefix (with 54 leading zeros) is currently used.

And how it applies for PPP? It is documented in  [RFC 5072 _IP Version 6 over PPP_, section 4.1. _Interface Identifier_](https://tools.ietf.org/html/rfc5072#section-4.1) and [section 5. _Stateless Autoconfiguration and Link-Local Addresses_](https://tools.ietf.org/html/rfc5072#section-5).

PPP is point to point link and both IPCP (for IPv4) and IPV6CP (for IPv6) PPP control protocols exchange just one address without prefix/netmask.

So technically prefix /128 for IPv6 Link-Local address for PPP is also correct as on PPP link there are no other clients and then kernel does not have to try routing/forwarding packets for Link-Local address over PPP link if that address does not match Link-Local address of other end of PPP link.

So I think there is nothing wrong with using either /64 or /128 for PPP IPv6 Link-Local addresses. Usage of /128 is just optimization for kernel routing algorithms.

**Comment by Neustradamus** [comment]
@pali: Thanks for your reply!

So you confirm that the value can be changed and must not be hardcoded?

Who can do a PR and have a release soon?

**Comment by pali** [comment]
> So you confirm that the value can be changed and must not be hardcoded?

Do you see somewhere in RFC 5072 that prefix is exchanged in IPV6CP protocol?

**Comment by pali** [comment]
In my opinion this PPP IPv6 link-local address should be set with prefix /128 (one address) as @joakim-tjernlund wrote in the first post.

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by pali** [comment]
Also just to note that pppd assigns for IPv4 also just /32 (=255.255.255.255) netmask (=one address).

**Comment by pali** [comment]
I created PR to set IPv6 prefix to /128: https://github.com/paulusmack/ppp/pull/162

**Comment by Neustradamus** [comment]
@pali: Thanks for your PR :)

@paulusmack: I ask you again ^^
What do you think?

**Comment by Neustradamus** [comment]
@pali: Thanks for your PR :)

@paulusmack: I ask you again ^^
What do you think?
