### ISSUE TITLE
pppd does not respond to SIGINT

### ISSUE THREAD

**Issue by argumemnon** [paulusmack/ppp#125]
On macOS Mojave 10.14.3, after a successful connection to a peer, either via `pppd call` or `pppd file`, issuing Ctrl-C (SIGINT) does not terminate the ppp call. The process must be terminated via `kill` instead.

**Comment by paulusmack** [comment]
What version of pppd is this? We had a problem like this some time ago but it is fixed as of ppp-2.4.5 as far as I know.

**Comment by argumemnon** [comment]
It doesn't look like whatever version I'm using has a flag to print the version. Any ideas how to check?

**Comment by paulusmack** [comment]
pppd --version. If your pppd doesn't have that then it's really old (i.e. before v2.3.0).

**Comment by pali** [comment]
Also sending SIGINT or SIGKILL via `kill` does not work correctly when using pppd for PPPoE. I prepared fix in following pull reuquest here: https://github.com/paulusmack/ppp/pull/148

**Comment by paulusmack** [comment]
Is this still an issue with the current pppd source?

**Comment by pali** [comment]
I was not able to reproduce it on Linux with my patch #148 but I'm not original reporter.
