### ISSUE TITLE
CCP / MPPE + peer with confrej loops forever.

### ISSUE THREAD

**Issue by nihilus** [paulusmack/ppp#127]
You basically end up in a send-reject loop for ever if you don't explicitly set mppe or nomppe due to the flawed logic in ccp.c handling of rejected CCP options. It looks if we actually get MPPE back from the other peer when the allowed options must be checked as well and cleared if MPPE is rejected.

**Comment by paulusmack** [comment]
Can you post an example log showing this behaviour?

**Comment by nihilus** [comment]
Never mind, I used the mppc/mppe patch and the bug was in it.
