### ISSUE TITLE
Improper null termination in getword() can cause OOB read by strlen()

### ISSUE THREAD

**Issue by flozilla** [paulusmack/ppp#130]
pppd parses files using the function getword(). When getword() is executed on a file that contains a string longer than 1023 bytes, it uses the option_error() function to print a warning that the parsed string, which is stored in the variable "word", is >= MAXWORDLEN = 1024 bytes long. However, "word" is null terminated after option_error() is executed (see options.c:1382-1390):

```
    /*
     * Warn if the word was too long, and append a terminating null.
     */
    if (len >= MAXWORDLEN) {
	option_error("warning: word in file %s too long (%.20s...)",
		     filename, word);
	len = MAXWORDLEN - 1;
    }
    word[len] = 0;
```

Calling option_error() eventually invokes the function vslprintf(), which executes strlen() on "word" (see utils.c:388). Because "word" is improperly null terminated, this leads to an OOB read by strlen(). IMHO, potential consequences of an improper null termination, e.g., described in [CWE-170](https://cwe.mitre.org/data/definitions/170.html), do not apply to this case, which is why this bug is not security sensitive.

To replicate this bug, simply generate a file that contains a string >= 1024 bytes and execute "pppd file <generated_file>".

To fix this bug, I would propose to set word[MAXWORDLEN - 1] = 0 before option_error() is executed.

**Comment by paulusmack** [comment]
Fixed by c10c3c7c. And b311e98b should help defend against similar things elsewhere.
