### ISSUE TITLE
Add support for EAP-MSCHAPv2

### ISSUE THREAD

**Issue by enaess** [paulusmack/ppp#138]
There is an implementation available here. I also created a branch for this fix here: https://github.com/enaess/ppp-eap-mschapv2

https://w3logistics.com/blog/archives/438-EAP-MSCHAPv2-for-pppd-2-4-7.html

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

Can you look for it?

Thanks in advance.

**Comment by Neustradamus** [comment]
The PR is here: https://github.com/paulusmack/ppp/pull/139

**Comment by enaess** [comment]
Okay, let me do this again against the latest tip of master branch.

**Comment by Neustradamus** [comment]
@enaess: Thanks, a new PR is here:
- https://github.com/paulusmack/ppp/pull/175

@paulusmack: Can you look?

**Comment by Neustradamus** [comment]
@enaess, @tisj: Please look @paulusmack comments :)
- https://github.com/paulusmack/ppp/pull/175
- https://github.com/paulusmack/ppp/pull/177

I really hope that your good job will be merged soon to have a new perfect version before Debian 11 freeze, after it, the next will be in 2023...

**Comment by enaess** [comment]
@Neustradamus @paulusmack 

Added new pull request that contains all the changes to add EAP-MSCHAPv2. 

Please have a look at #211
