### ISSUE TITLE
pppd doesn't terminate on signal 15

### ISSUE THREAD

**Issue by ghost** [paulusmack/ppp#14]
We use a daemon to restart pppd to recover when connections are not working properly. However, the recovery mechanism failed at least once, because pppd doesn't respond to SIGTERM.

We are using pppd 2.4.5 on a Multi-Tech MTCDP-G2-GP with core-cdp version 2.2.2.

Herewith a more detailed description of the recovery mechanism and some log snippets.

The recovery dameon sends the TERM signal to pppd using `touch /tmp/reset-radio; killall pppd`. It does so once per 30 minutes (max). pppd is configured to run an init script. This init scripts reset the GSM-modem if the file /tmp/reset-radio exists.

$ cat options
/dev/ttyS1
lock
debug
init /var/config/ppp/modem_init

linkname ppp0
230400
defaultroute
replacedefaultroute
usepeerdns
ipcp-max-failure 4
ipcp-restart 10
lcp-echo-failure 4
lcp-echo-interval 30
noauth
show-password
noccp
crtscts
persist
novj
modem
maxfail 10
holdoff 30

$ cat /var/config/ppp/modem_init
# !/bin/bash

if [ ! -e /tmp/reset-radio ] ; then
  exit 0 # no need to reset modem
fi

echo 0 > /sys/devices/platform/mtcdp/radio-reset
sleep 8
rm /tmp/reset-radio

However, as you can see in the following log, pppd doesn't terminate (the pid doesn't change for over 2 weeks). Except for "Terminating on signal 15", there is no other output from pppd, nor from chat.

Jul 12 12:52:09 mtcdp daemon.info pppd[5776]: Terminating on signal 15
Jul 12 13:22:11 mtcdp daemon.info pppd[5776]: Terminating on signal 15
Jul 12 13:52:13 mtcdp daemon.info pppd[5776]: Terminating on signal 15
[........ this continues for many days) ......]
Aug  4 02:56:13 mtcdp daemon.info pppd[5776]: Terminating on signal 15

The problem restored when the modem was reset by manually echoing 0 to a designated device to trigger a reset of the modem chip. After that, pppd got unstuck with the following log lines:
Aug  4 03:26:42 mtcdp daemon.info pppd[5776]: Hangup (SIGHUP)
Aug  4 03:26:42 mtcdp daemon.notice pppd[5776]: Modem hangup
Aug  4 03:26:42 mtcdp daemon.notice pppd[5776]: Connection terminated.
Aug  4 03:26:43 mtcdp daemon.info pppd[5776]: Exit.

Prior to pppd getting stuck, a serial loopback was detected (see log snippet below). This may or may not be related. This unit has been running without problems for over a year, and we haven't noticed a serial loopback before.

Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x33 <magic 0xcab2d158>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x33 <magic 0xcab2d158>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x34 <asyncmap 0x0> <magic 0x7702a5a7> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x34 <asyncmap 0x0> <magic 0x7702a5a7> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x34 <magic 0xf5cc024d>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x34 <magic 0xf5cc024d>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x35 <asyncmap 0x0> <magic 0x2d7bf86a> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x35 <asyncmap 0x0> <magic 0x2d7bf86a> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x35 <magic 0xc75b0bc8>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x35 <magic 0xc75b0bc8>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x36 <asyncmap 0x0> <magic 0xae6d13a9> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x36 <asyncmap 0x0> <magic 0xae6d13a9> <pcomp> <accomp>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x36 <magic 0x638bcda>]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x36 <magic 0x638bcda>]
Jul 12 12:50:57 mtcdp daemon.notice pppd[5776]: Serial line is looped back.
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP TermReq id=0x37 "Loopback detected"]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP TermReq id=0x37 "Loopback detected"]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: sent [LCP TermAck id=0x37]
Jul 12 12:50:57 mtcdp daemon.debug pppd[5776]: rcvd [LCP TermAck id=0x37]
Jul 12 12:50:57 mtcdp daemon.notice pppd[5776]: Connection terminated.
Jul 12 12:51:29 mtcdp daemon.debug pppd[5776]: Script /var/config/ppp/modem_init finished (pid 7447), status = 0x0
Jul 12 12:51:29 mtcdp daemon.info pppd[5776]: Serial port initialized.
Jul 12 12:51:29 mtcdp local2.info chat[7450]: send (\d+++\d^M)
Jul 12 12:51:31 mtcdp local2.info chat[7450]: send (ATZ^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: expect (OK)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: +++^MATZ^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK
Jul 12 12:51:32 mtcdp local2.info chat[7450]:  -- got it
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: abort on (NO CARRIER)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: abort on (BUSY)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: abort on (CONNECTED)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: abort on (ERROR)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT+CPIN?^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT+CSQ^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT+CREG?^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: expect (OK)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: ^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK
Jul 12 12:51:32 mtcdp local2.info chat[7450]:  -- got it
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (AT+CGDCONT=1,"IP","internet.beeline.kz"^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: expect (OK)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: ^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT+CPIN?^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: +CPIN: READY^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT+CSQ^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: +CSQ: 31,0^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: ^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK
Jul 12 12:51:32 mtcdp local2.info chat[7450]:  -- got it
Jul 12 12:51:32 mtcdp local2.info chat[7450]: send (ATD_99_**1#^M)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: expect (CONNECT)
Jul 12 12:51:32 mtcdp local2.info chat[7450]: ^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT+CREG?^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: +CREG: 0,1^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: ^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: AT+CGDCONT=1,"IP","internet.beeline.kz"^M^M
Jul 12 12:51:32 mtcdp local2.info chat[7450]: OK^M
Jul 12 12:51:33 mtcdp local2.info chat[7450]: ATD*99***1#^M^M
Jul 12 12:51:33 mtcdp local2.info chat[7450]: CONNECT
Jul 12 12:51:33 mtcdp local2.info chat[7450]:  -- got it
Jul 12 12:51:33 mtcdp local2.info chat[7450]: send (^M)
Jul 12 12:51:33 mtcdp daemon.debug pppd[5776]: Script /usr/sbin/chat -v -t 90 -f /etc/ppp/peers/gsm_chat -T internet.beeline.kz finished (pid 7449), status = 0x0
Jul 12 12:51:33 mtcdp daemon.info pppd[5776]: Serial connection established.
Jul 12 12:51:33 mtcdp daemon.debug pppd[5776]: using channel 449
Jul 12 12:51:33 mtcdp daemon.info pppd[5776]: Using interface ppp0
Jul 12 12:51:33 mtcdp daemon.notice pppd[5776]: Connect: ppp0 <--> /dev/ttyS1
Jul 12 12:51:34 mtcdp daemon.warn pppd[5776]: Warning - secret file /etc/ppp/pap-secrets has world and/or group access
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x38 <asyncmap 0x0> <magic 0x330ce210> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x38 <asyncmap 0x0> <magic 0x330ce210> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x38 <magic 0x67bcec8e>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x38 <magic 0x67bcec8e>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x39 <asyncmap 0x0> <magic 0xeedf8a51> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x39 <asyncmap 0x0> <magic 0xeedf8a51> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x39 <magic 0x885728b4>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x39 <magic 0x885728b4>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3a <asyncmap 0x0> <magic 0xd84b1277> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3a <asyncmap 0x0> <magic 0xd84b1277> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3a <magic 0x6fc39098>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3a <magic 0x6fc39098>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3b <asyncmap 0x0> <magic 0x2042c322> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3b <asyncmap 0x0> <magic 0x2042c322> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3b <magic 0x605a6061>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3b <magic 0x605a6061>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3c <asyncmap 0x0> <magic 0xf35fcb8d> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3c <asyncmap 0x0> <magic 0xf35fcb8d> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3c <magic 0xbf4c31dc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3c <magic 0xbf4c31dc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3d <asyncmap 0x0> <magic 0xb3cc9578> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3d <asyncmap 0x0> <magic 0xb3cc9578> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3d <magic 0xd42e0fcc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3d <magic 0xd42e0fcc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3e <asyncmap 0x0> <magic 0x7c7d215c> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3e <asyncmap 0x0> <magic 0x7c7d215c> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3e <magic 0x582a736a>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3e <magic 0x582a736a>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x3f <asyncmap 0x0> <magic 0x9b331f89> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x3f <asyncmap 0x0> <magic 0x9b331f89> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x3f <magic 0xe75c39fc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x3f <magic 0xe75c39fc>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x40 <asyncmap 0x0> <magic 0x705321dd> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x40 <asyncmap 0x0> <magic 0x705321dd> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x40 <magic 0x767156b0>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x40 <magic 0x767156b0>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfReq id=0x41 <asyncmap 0x0> <magic 0x7e535b2f> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfReq id=0x41 <asyncmap 0x0> <magic 0x7e535b2f> <pcomp> <accomp>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP ConfNak id=0x41 <magic 0xa374451f>]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP ConfNak id=0x41 <magic 0xa374451f>]
Jul 12 12:51:34 mtcdp daemon.notice pppd[5776]: Serial line is looped back.
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP TermReq id=0x42 "Loopback detected"]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP TermReq id=0x42 "Loopback detected"]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: sent [LCP TermAck id=0x42]
Jul 12 12:51:34 mtcdp daemon.debug pppd[5776]: rcvd [LCP TermAck id=0x42]
Jul 12 12:51:34 mtcdp daemon.notice pppd[5776]: Connection terminated.
Jul 12 12:52:06 mtcdp daemon.debug pppd[5776]: Script /var/config/ppp/modem_init finished (pid 7795), status = 0x0
Jul 12 12:52:06 mtcdp daemon.info pppd[5776]: Serial port initialized.

**Comment by paulusmack** [comment]
Closing this issue as stale. Though, if someone had an easy reproducer I would investigate further.
