### ISSUE TITLE
Feature Request: setenv_call_file

### ISSUE THREAD

**Issue by iddq** [paulusmack/ppp#147]
Can you please merge the debian setenv_call_file patch?

> patch -p0 < ../ppp-2.4.7/debian/patches/setenv_call_file

**Comment by paulusmack** [comment]
No, because there is no authorship information or sign-off in the patch, nor any description of why the change was made.

**Comment by Neustradamus** [comment]
@iddq: Can you contact the PPP Debian team?
It will be nice if the team can create a PR directly here...

https://packages.debian.org/sid/ppp
- Chris Boot (Page QA) : https://qa.debian.org/developer.php?login=bootc%40debian.org
- Marco d'Itri (Page QA) : https://qa.debian.org/developer.php?login=md%40linux.it

**Comment by paulusmack** [comment]
Fixed by commit 861202529f60.
