### ISSUE TITLE
pppd ignore PADT while running as PPPoE client

### ISSUE THREAD

**Issue by longwdl** [paulusmack/ppp#15]
1. disable lcp-echo-interval
2. start pppd as PPPoE client
3. close the PPPoE server, PADT is sent by the server (RouterOS 5.24 is used as the server)
4. pppd does not exit

**Comment by farnz** [comment]
This is a kernel bug, if you're using rp-pppoe.so; the kernel eats the PADT and does not react to it.

https://patchwork.ozlabs.org/patch/444717/ has a kernel-side fix for it.

**Comment by farnz** [comment]
You also want pull request 33 once you've taken the kernel-side fix, to suppress a false positive error message.

**Comment by farnz** [comment]
The kernel fix will be in Linux 4.1 and later.

**Comment by paulusmack** [comment]
Fixed in kernel.
