### ISSUE TITLE
Compile wpa_supplicant 0.7.3 with openssl 1.0.0 fails in /src/crypto/tls_openssl.c

### ISSUE THREAD

**Issue by rh100605** [paulusmack/ppp#152]
I am trying too repair a corrupted imbedded Linux installation in a wifi attached picture frame using a Samsung 32bit armv7 processor. Many files were corrupted including ldconfig and wpa_supplicant 0.7.3. 
I cannot get network access without wpa_supplicant for a software upgrade so I decided to make a new one

When I make ( on Raspberry pi)  wpa_supplicant version 0.7.3 it fails at lines 1267 and 2215 in /src/crypto/tls_openssl.c . ( with deprecated in openssl 1.0.0)

tried again with hostap_1.0_rl1
./src/crypto/tls_openssl.c: In function ‘tls_init’:
../src/crypto/tls_openssl.c:745:2: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
  ssl = SSL_CTX_new(TLSv1_method());
  ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from ../src/crypto/tls_openssl.c:23:
/usr/include/openssl/ssl.h:1877:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^~~~~~~~~~~~~~~~~~
../src/crypto/tls_openssl.c: In function ‘tls_deinit’:
../src/crypto/tls_openssl.c:783:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from ../src/crypto/tls_openssl.c:23:
/usr/include/openssl/err.h:261:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^~~~~~~~~~~~~~~~~~
../src/crypto/tls_openssl.c: In function ‘tls_load_ca_der’:
../src/crypto/tls_openssl.c:1285:40: error: dereferencing pointer to incomplete type ‘SSL_CTX’ {aka ‘struct ssl_ctx_st’}
  lookup = X509_STORE_add_lookup(ssl_ctx->cert_store,
                                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_get_keys’:
../src/crypto/tls_openssl.c:2293:24: error: dereferencing pointer to incomplete type ‘SSL’ {aka ‘struct ssl_st’}
  if (ssl == NULL || ssl->s3 == NULL || ssl->session == NULL)
                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_resumed’:
../src/crypto/tls_openssl.c:2545:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Makefile:1457: ../src/crypto/tls_openssl.o] Error 1

I read a post that suggests I should use a later version of the tls_openssl,c file . I tried vsn 2.9 but this has other includes that I do not know how to satisfy.
Can you help

**Comment by paulusmack** [comment]
Does this have anything to do with pppd?
