### ISSUE TITLE
restart systemd-resolved.service drops PPP entries

### ISSUE THREAD

**Issue by jidanni** [paulusmack/ppp#167]
This is either a systemd bug
https://github.com/systemd/systemd/issues/17004
or a ppp bug (that ppp cannot deal properly with current systemd.) Still present in ppp-2.4.8 .

**Comment by paulusmack** [comment]
It seems like the debian packaging of pppd has not been updated to use whatever the "correct" way to supply new DNS servers to systemd-resolved is. Pppd (this project) writes /etc/ppp/resolv.conf, not /etc/resolv.conf, and it's up to the distro to connect that to whatever it needs to be connected to. You need to poke your distro's ppp package maintainer.

**Comment by jidanni** [comment]
OK I told them in https://bugs.debian.org/970076 . Thanks.
