### ISSUE TITLE
Be sure to add a comment as to who wrote resolv.conf 

### ISSUE THREAD

**Issue by jidanni** [paulusmack/ppp#168]
/etc/ppp/ip-up.d/0000usepeerdns might write resolv.conf or files that links to.

That is great, but without a comment:
```
# updated by /etc/ppp/ip-up.d/0000usepeerdns , Nov. 23, 2020 01:23 UTC
```
it just adds to the [mystery](https://unix.stackexchange.com/a/527581/179494) of who is updating that file.

**Comment by paulusmack** [comment]
That file comes from your distro's packaging of pppd, not this project. File a bug with your distro.

**Comment by jidanni** [comment]
OK. Made https://bugs.debian.org/970075 .

**Comment by enaess** [comment]
Thanks @jidanni - I've posted a patch to the Ubuntu folks too, but since they are really just adding it on top of Debian; fixing it Debian would propagate the change.

**Comment by Neustradamus** [comment]
@bootc: It is a ticket in Debian system, please look it.
