### ISSUE TITLE
INSTROOT not respected/honoured (make INSTROOT=path install)

### ISSUE THREAD

**Issue by nylon0700** [paulusmack/ppp#173]
No matter what, under linux, INSTROOT is not respected by each relevant makefile.
Even after configure --prefix=.

[ppp-2.4.8.orx.pppol2tp.makefile.linux.patch.gz](https://github.com/paulusmack/ppp/files/5419001/ppp-2.4.8.orx.pppol2tp.makefile.linux.patch.gz)

**Comment by Neustradamus** [comment]
@nylon0700: Thanks, a recall to @paulusmack!

Linked to:
- https://github.com/paulusmack/ppp/pull/54
- https://github.com/paulusmack/ppp/pull/99

**Comment by paulusmack** [comment]
This should be fixed now. Let me know if not.
