### ISSUE TITLE
ip-up sometimes called twice

### ISSUE THREAD

**Issue by cmcqueen** [paulusmack/ppp#18]
I'm using pppd with a satellite network and its dial-up servers. I find that sometimes, pppd prints the connection info twice to stdout, and calls `/etc/ppp/ip-up` twice. E.g.

```
Sep  2 06:06:44 (none) local2.notice pppd[17373]: Connect: ppp0 <--> /dev/ttySP0
Sep  2 06:07:02 (none) local2.notice pppd[17373]: CHAP authentication succeeded
Sep  2 06:07:13 (none) local2.notice pppd[17373]: local  IP address 192.168.20.81
Sep  2 06:07:13 (none) local2.notice pppd[17373]: remote IP address 192.168.20.254
Sep  2 06:07:13 (none) local2.notice pppd[17373]: primary   DNS address 199.2.252.10
Sep  2 06:07:13 (none) local2.notice pppd[17373]: secondary DNS address 204.97.212.10
Sep  2 06:07:16 (none) local2.notice pppd[17373]: Compression disabled by peer.
Sep  2 06:07:18 (none) local2.notice pppd[17373]: local  IP address 192.168.20.81
Sep  2 06:07:18 (none) local2.notice pppd[17373]: remote IP address 192.168.20.254
Sep  2 06:07:18 (none) local2.notice pppd[17373]: primary   DNS address 199.2.252.10
Sep  2 06:07:18 (none) local2.notice pppd[17373]: secondary DNS address 204.97.212.10
```

`/etc/ppp/ip-up` was called twice, at 06:07:14 and 06:07:18.

Why might pppd do both the printing of address info twice, and calling `/etc/ppp/ip-up` twice? Is this considered "normal" or a bug?

**Comment by paulusmack** [comment]
This can happen if the IPCP Configure-ack that we sent got lost. The peer resends its configure-req after a timeout, and pppd then has to renegotiate IPCP according to the PPP standards. So it is expected, and not a bug.
