### ISSUE TITLE
Add automated build in repo.

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [paulusmack/ppp#180]
Hi,

I might be able to create two GitHub actions that would build a Linux version and a Solaris version of latest PPP on each repo push.
This could help in investigating build problems and speed up __P() macro removal.
I'm planning to use [this action](https://github.com/vmactions/solaris-vm) to add Solaris support (never tried, don't know if it works).

What do you think about this ? Should I start working on it or this is useless ?

**Comment by paulusmack** [comment]
Ah, interesting that you can get a Solaris VM to build in. Building for Linux is easy enough but I have no way to do test builds on Solaris (other than by asking @carlsonj to do one).

I think this would be a great idea. If you can set it up to build for more than one Linux environment that would be even better. I'm thinking of different architectures (x86, arm, powerpc) and different environments (e.g. using glibc/uclibc/musl, buildroot vs. hosted environments, fedora/debian/opensuse etc.).

**Comment by RICCIARDI-Adrien** [comment]
Great, I'm working on it !

**Comment by RICCIARDI-Adrien** [comment]
That was useful, I get a problem with musl build (see https://github.com/RICCIARDI-Adrien/ppp/runs/1631728970?check_suite_focus=true) :
```
/home/runner/work/ppp/ppp/buildroot/output/host/bin/i686-buildroot-linux-musl-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -DHAVE_PATHS_H -DIPX_CHANGE -DHAVE_MMAP -I../include '-DDESTDIR="/usr"' -DCHAPMS=1 -DMPPE=1 -DUSE_EAPTLS=1 -DHAS_SHADOW -DHAVE_CRYPT_H=1 -DHAVE_LOGWTMP=1 -DUSE_CRYPT=1 -DHAVE_MULTILINK -DUSE_TDB=1 -DPLUGIN -DPPP_FILTER -DINET6=1 -DMAXOCTETS  -Wl,-E -o pppd main.o magic.o fsm.o lcp.o ipcp.o upap.o chap-new.o md5.o ccp.o ecp.o auth.o options.o demand.o utils.o sys-linux.o ipxcp.o tty.o eap.o chap-md5.o session.o md4.o chap_ms.o sha1.o eap-tls.o pppcrypt.o multilink.o tdb.o spinlock.o ipv6cp.o eui64.o -lrt -lssl -lcrypt -lutil -lcrypto -ldl -lpcap
/home/runner/work/ppp/ppp/buildroot/output/host/lib/gcc/i686-buildroot-linux-musl/9.3.0/../../../../i686-buildroot-linux-musl/bin/ld: session.o: in function `session_start':
session.c:(.text+0x13d): undefined reference to `logwtmp'
/home/runner/work/ppp/ppp/buildroot/output/host/lib/gcc/i686-buildroot-linux-musl/9.3.0/../../../../i686-buildroot-linux-musl/bin/ld: session.o: in function `session_end':
session.c:(.text+0x1a1): undefined reference to `logwtmp'
collect2: error: ld returned 1 exit status
```
musl seems to not provide `logwtmp()`. Maybe enabling ppp internal implementation of `logwtmp()` for musl could do the trick, but I did not try this yet.

**Comment by paulusmack** [comment]
This should be OK now; commit 248c11d375c5 fixes this problem.

**Comment by RICCIARDI-Adrien** [comment]
I confirm that this problem is fixed, thank you.

**Comment by paulusmack** [comment]
I merged #208.

How do I set up github to run the tests on all pull requests?

Also, I see that buildroot modifies various things in the PPP package before building, and you remove some of the code that does those modifications. Are we vulnerable to getting broken by upstream buildroot changes?

**Comment by RICCIARDI-Adrien** [comment]
Hi,

I made another pull request that enables tests for pull requests (#214).

I selected a stable version of Buildroot, so it won't change anymore and it should not be broken by upstream changes. Moreover, when a new PPP version is released, I can help upstreaming it in Buildroot, so we can later get rid of the changes made by the CI.

Next move it to try Solaris build !

**Comment by RICCIARDI-Adrien** [comment]
Solaris build is near to be ready, it uses Solaris 11.4 (SunOS solaris 5.11 11.4.0.15.0) and gcc 7.3.0.
Latest build (https://github.com/RICCIARDI-Adrien/ppp/runs/1637972927?check_suite_focus=true) allowed to spot the following error :
```
gcc -I../include -DSVR4 -DSOL2 -O2 '-DDESTDIR="/usr/local"' -DHAS_SHADOW -DPLUGIN -DINET6 -DUSE_CRYPT -DCHAPMS -DMSLANMAN -DHAVE_CRYPT_H -DMPPE -DUSE_EAPTLS  -c  sys-solaris.c
sys-solaris.c:2318:71: error: unknown type name ‘maxlen’
 dlpi_get_reply(int fd, union DL_primitives *reply, int expected_prim, maxlen)
                                                                       ^~~~~~
sys-solaris.c:261:12: warning: ‘dlpi_get_reply’ used but never defined
 static int dlpi_get_reply(int, union DL_primitives *, int, int);
            ^~~~~~~~~~~~~~
*** Error code 1
make: Fatal error: Command failed for target `sys-solaris.o'
```
I think `maxlen` should be an `int`, but I have not checked in the code.

**Comment by carlsonj** [comment]
I sent a patch for that.

<carlsonj@workingcode.com>

**Comment by carlsonj** [comment]
On 1/2/21 7:21 PM, Adrien RICCIARDI wrote:
> Solaris build is near to be ready, it uses Solaris 11.4 (SunOS solaris 
> 5.11 11.4.0.15.0) and gcc 7.3.0.
> Latest build 
> (https://github.com/RICCIARDI-Adrien/ppp/runs/1637972927?check_suite_focus=true 
> <https://github.com/RICCIARDI-Adrien/ppp/runs/1637972927?check_suite_focus=true>) 
> allowed to spot the following error :
> 
> |gcc -I../include -DSVR4 -DSOL2 -O2 '-DDESTDIR="/usr/local"' 
> -DHAS_SHADOW -DPLUGIN -DINET6 -DUSE_CRYPT -DCHAPMS -DMSLANMAN 
> -DHAVE_CRYPT_H -DMPPE -DUSE_EAPTLS -c sys-solaris.c 
> sys-solaris.c:2318:71: error: unknown type name ‘maxlen’ 
> dlpi_get_reply(int fd, union DL_primitives *reply, int expected_prim, 
> maxlen) ^~~~~~ sys-solaris.c:261:12: warning: ‘dlpi_get_reply’ used but 
> never defined static int dlpi_get_reply(int, union DL_primitives *, int, 
> int); ^~~~~~~~~~~~~~ *** Error code 1 make: Fatal error: Command failed 
> for target `sys-solaris.o' |
> 
> I think |maxlen| should be an |int|, but I have not checked in the code.

Here's the patch I sent.

-- 
James Carlson         42.703N 71.076W         <carlsonj@workingcode.com>

**Comment by RICCIARDI-Adrien** [comment]
Hi @carlsonj,
The attached patch seems to be missing. Did you send it directly to @paulusmack ?
You might do a pull request if you want, this may be simpler for @paulusmack to merge.

**Comment by Neustradamus** [comment]
@carlsonj: You need to connect on GitHub and publish your patch here with "Insert code" feature.

**Comment by carlsonj** [comment]
On 1/3/21 10:03 AM, Adrien RICCIARDI wrote:
> Hi @carlsonj <https://github.com/carlsonj>,
> The attached patch seems to be missing. Did you send it directly to 
> @paulusmack <https://github.com/paulusmack> ?
> You might do a pull request if you want, this may be simpler for 
> @paulusmack <https://github.com/paulusmack> to merge.

I just checked.  It was on the message I sent.  Here it is again.

-- 
James Carlson         42.703N 71.076W         <carlsonj@workingcode.com>

From f86e254bdb4d529aae293cbe3e04ad8f1d52b0d4 Mon Sep 17 00:00:00 2001
From: James Carlson <carlsonj@workingcode.com>
Date: Wed, 30 Dec 2020 09:55:12 -0500
Subject: [PATCH] Repair compilation issues on Solaris: there's no "ifr_mtu" on
 the legacy BSD interface; it's "ifr_metric" and old K&R style implied 'int'
 can't be used with modern function declarations.

---
 pppd/sys-solaris.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/pppd/sys-solaris.c b/pppd/sys-solaris.c
index d96d23c..7126428 100644
--- a/pppd/sys-solaris.c
+++ b/pppd/sys-solaris.c
@@ -261,7 +261,7 @@ static int get_hw_addr(char *, u_int32_t, struct sockaddr *);
 static int get_hw_addr_dlpi(char *, struct sockaddr *);
 static int dlpi_attach(int, int);
 static int dlpi_info_req(int);
-static int dlpi_get_reply(int, union DL_primitives *, int, int);
+static int dlpi_get_reply(int, union DL_primitives *, int, size_t);
 static int strioctl(int, int, void *, int, int);
 
 #ifdef SOL2
@@ -1546,7 +1546,7 @@ netif_get_mtu(int unit)
     error("ioctl(SIOCGIFMTU): %m (line %d)", __LINE__);
     return 0;
     }
-    return ifr.ifr_mtu;
+    return ifr.ifr_metric;
 }
 
 /*
@@ -2357,7 +2357,7 @@ dlpi_info_req(int fd)
 }
 
 static int
-dlpi_get_reply(int fd, union DL_primitives *reply, int expected_prim, maxlen)
+dlpi_get_reply(int fd, union DL_primitives *reply, int expected_prim, size_t maxlen)
 {
     struct strbuf buf;
     int flags, n;
-- 
2.28.0

**Comment by Neustradamus** [comment]
Like I have not commented here before, I had not your previous comment/email, @RICCIARDI-Adrien has maybe in mailbox, I am not sure.
But in the GitHub interface, there is always a lot of data shortened from email.
Now, there is in your last comment/email, if we click on "…" (there was not not before).
Thanks :)

**Comment by RICCIARDI-Adrien** [comment]
Thank you @carlsonj for sending the patch another time.
I didn't receive any email or notification from GitHub, maybe something went wrong in their infrastructure.

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Look settings in https://github.com/settings/profile -> https://github.com/settings/notifications

**Comment by RICCIARDI-Adrien** [comment]
@Neustradamus : Thank you, I double-checked and everything is fine. Don't know what happened...

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: No problem, in our case, the most important part is:
- Participating | Notifications for the conversations you are participating in, or if someone cites you with an @.

**Comment by paulusmack** [comment]
This all looks great now. I think this issue can be closed - any objections?

**Comment by paulusmack** [comment]
I notice that the checks seem to take quite a long time. It looks like we are doing an entire build of buildroot, including building a kernel and the C library and everything, inside a qemu emulation of each architecture. This is OK for now but in future perhaps we could look at slimming down the buildroot config so as not to build any more than we really need to.

**Comment by RICCIARDI-Adrien** [comment]
Yes, this issue can be closed. If you agree, I would like to add one more CI test : a simple Ubuntu build.
Yes, checks are quite slow... OK, I will try to trim Buildroot configurations later to save some time.

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Good job about compilation tests!
Have you looked to reduce the process?
To have more quick tests.

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: When there is a new commit in a PR, the test is launched a new time?

**Comment by RICCIARDI-Adrien** [comment]
Hi @Neustradamus,
No, I didn't had the time yet to improve build times...
Yes, tests are launched every time there is a pull on master or any pull request branch.

**Comment by Neustradamus** [comment]
Thanks, it is good, the @yarda PR test is relaunched after the force-pushed ^^
