### ISSUE TITLE
pppol2tp.c:50:31: fatal error: linux/if_pppol2tp.h: No such file or directory

### ISSUE THREAD

**Issue by sn01615** [paulusmack/ppp#20]
[root@MyServer ppp-2.4.7]#make
cd chat; make  all
make[1]: Entering directory `/root/ppp-2.4.7/chat'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/root/ppp-2.4.7/chat'
cd pppd/plugins; make  all
make[1]: Entering directory`/root/ppp-2.4.7/pppd/plugins'
for d in rp-pppoe pppoatm pppol2tp radius; do make -w -C $d all; done
make[2]: Entering directory `/root/ppp-2.4.7/pppd/plugins/rp-pppoe'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/root/ppp-2.4.7/pppd/plugins/rp-pppoe'
make[2]: Entering directory`/root/ppp-2.4.7/pppd/plugins/pppoatm'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/root/ppp-2.4.7/pppd/plugins/pppoatm'
make[2]: Entering directory `/root/ppp-2.4.7/pppd/plugins/pppol2tp'
/usr/local/bin/gcc -O2 -g -I. -I../.. -I../../../include -fPIC -c -o pppol2tp.o pppol2tp.c
pppol2tp.c:50:31: fatal error: linux/if_pppol2tp.h: No such file or directory
 #include <linux/if_pppol2tp.h>
                               ^
compilation terminated.
make[2]: *** [pppol2tp.o] Error 1
make[2]: Leaving directory`/root/ppp-2.4.7/pppd/plugins/pppol2tp'
make[2]: Entering directory `/root/ppp-2.4.7/pppd/plugins/radius'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/root/ppp-2.4.7/pppd/plugins/radius'
make[1]: Leaving directory`/root/ppp-2.4.7/pppd/plugins'
cd pppd; make  all
make[1]: Entering directory `/root/ppp-2.4.7/pppd'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/root/ppp-2.4.7/pppd'
cd pppstats; make  all
make[1]: Entering directory`/root/ppp-2.4.7/pppstats'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/root/ppp-2.4.7/pppstats'
cd pppdump; make  all
make[1]: Entering directory `/root/ppp-2.4.7/pppdump'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/root/ppp-2.4.7/pppdump'
[root@MyServer ppp-2.4.7]#

**Comment by paulusmack** [comment]
Is this still an issue? If so, we would need more information about the environment you're trying to compile this in (e.g. architecture, Linux distribution, etc.). For now I am closing this but we can reopen it if you still need help.
