### ISSUE TITLE
pppd can not send PPPoE service name

### ISSUE THREAD

**Issue by kingiorikk** [paulusmack/ppp#21]
Dear Sir's:
I try to send below command, but pppd can not send pppoe service name, 
so what problem for below command？
Thanks.

command:
pppd unit 100 user auto password auto nodetach holdoff 4 maxfail 0 usepeerdns lcp-echo-interval 1 lcp-echo-failure 60 plugin libpppoe.so nas10_0  defaultroute noipdefault persist mtu 1492 mru 1492 plugin rp-pppoe.so rp_pppoe_service 'service_name' debug & 

debug message:
RP-PPPoE plugin version 3.8p compiled against pppd 2.4.5
Plugin rp-pppoe.so loaded.
RP-PPPoE plugin version 3.8p compiled against pppd 2.4.5
Send PPPOE Discovery V1T1 PADI session 0x0 length 17
 dst ff:ff:ff:ff:ff:ff  src 0:aa:bb:53:68:63
 [service-name ] [host-uniq  00 00 70 6b]

**Comment by paulusmack** [comment]
Should be fixed by cab58617 in ppp-2.4.6.
