### ISSUE TITLE
poff prints errors to stdout

### ISSUE THREAD

**Issue by safinaskar** [paulusmack/ppp#23]
poff, pon and maybe other scripts print errors to stdout instead of stderr. For example, I see the following in poff:

```
echo "$0: No pppd is running.  None ${DONE}."
```

But there should be:

```
echo "$0: No pppd is running.  None ${DONE}." >&2
```

Please, fix all this issues. (And if you want I can myself prepare such patch.)

**Comment by paulusmack** [comment]
Is this still an issue? Those scripts are really just examples of things that people have found useful. If you care to prepare a patch or a pull request (see Submitting-patches.md) I will look at it. For now I am closing this issue since it is very old.
