### ISSUE TITLE
make version making ppp non-reproducible

### ISSUE THREAD

**Issue by rpurdie** [paulusmack/ppp#233]
Hi, 

I've noticed that our builds on some systems are giving different results and the issue seems to depend on the version of bash used.

The issue is this code in pppd/Makefile.linux:

ifeq ($(shell echo '\\#include <utmp.h>' | $(CC) -E - 2>/dev/null | grep -q logwtmp && echo yes),yes)

on one system, it is injecting literally \\#include instead of #include which then means USE_LIBUTIL isn't set, -DHAVE_LOGWTMP=1 isn't added to CFLAGS and the internal utmplog() wrapper is used.

I tried swapping echo for printf but that didn't help, it simply doesn't run the makefile on a bash system if I remove the escape. I'm not entirely show what the best way to fix this is.

This is blocking Yocto Project from moving to 2.4.9 (but big thanks for the release!).

A working bash is GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
and a bash showing he issue is GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) (from an ubuntu 1604 system)

**Comment by rpurdie** [comment]
Best option I can find so far is to push the quoting from shell over to make with something like:

UTMPHEADER = "\\#include <utmp.h>"
ifeq ($(shell echo $(UTMPHEADER) | $(CC) -E - | grep -q logwtmp && echo yes),yes)

which then seems to work with both bash versions.

**Comment by rpurdie** [comment]
Further info, its not bash, its make that is causing the issue:

http://git.savannah.gnu.org/cgit/make.git/commit/?id=c6966b323811c37acedff05b576b907b06aea5f4

Basically comments in shell functions are escaped differently depending upon the make version. Fun. I'd suggest my change above is a reasonable workaround and needs to be applied for the crypt.h test too.

**Comment by rpurdie** [comment]
https://github.com/paulusmack/ppp/pull/234

**Comment by paulusmack** [comment]
Merged #234
