### ISSUE TITLE
Build failure with kernel < 4.3

### ISSUE THREAD

**Issue by ffontaine** [paulusmack/ppp#241]
`NETLINK_CAP_ACK` is used since commit c3af52231184ade3cf728ec60c9de9e87c2622ad however `NETLINK_CAP_ACK` is only available since kernel 4.3 and https://github.com/torvalds/linux/commit/0a6a3a23ea6efde079a5b77688541a98bf202721. Could you fix this issue or should we add a dependency on kernel being above 4.3 in buildroot?

**Comment by pali** [comment]
I'm planning to fix it, just I'm waiting for testing that proposed fix in https://github.com/paulusmack/ppp/issues/111#issuecomment-755321787 is really working. If you can test it and verify that IPv6 traffic is working fine, it would be great!

I have already sent patch for netlink.7 manpage:
https://lore.kernel.org/linux-man/20210110140027.14937-1-pali@kernel.org/T/#u

**Comment by pali** [comment]
Anybody for testing proposed change https://github.com/paulusmack/ppp/issues/111#issuecomment-755321787 ?
