### ISSUE TITLE
install upgrade pppd does not work

### ISSUE THREAD

**Issue by zingaro1972** [paulusmack/ppp#247]
Hi I treid upgrade of pppd package from 2.4.5 ( centos 7 OS ) from 2.4.7 and 2.4.9 but i have this error :
.  2.4.6 and 2.4.7 ./configure and make : return 
...................
DUSE_CRYPT=1 -DHAVE_MULTILINK -DUSE_TDB=1 -DPLUGIN -DPPP_FILTER -DINET6=1 -DMAXOCTETS -Wl,-E -o pppd main.o magic.o fsm.o lcp.o ipcp.o upap.o chap-new.o md5.o ccp.o ecp.o auth.o options.o demand.o utils.o sys-linux.o ipxcp.o tty.o eap.o chap-md5.o session.o md4.o chap_ms.o sha1.o pppcrypt.o multilink.o tdb.o spinlock.o ipv6cp.o eui64.o  -lcrypt -lutil -ldl -lpcap
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libpcap.so when searching for -lpcap
/usr/bin/ld: skipping incompatible //lib/libpcap.so when searching for -lpcap
/usr/bin/ld: skipping incompatible //usr/lib/libpcap.so when searching for -lpcap
/usr/bin/ld: cannot find -lpcap
collect2: error: ld returned 1 exit status
make[1]: *** [pppd] Error 1
make[1]: Leaving directory `/root/temp/pppdsource/ppp-ppp-2.4.6/pppd'
make: *** [all] Error 2

2.4.9 make:
cd pppd; make  all
make[1]: Entering directory `/root/temp/pppdsource/ppp-2.4.9/pppd'
cc -O2 -g -pipe -DHAVE_PATHS_H -DIPX_CHANGE -DHAVE_MMAP -pipe -I../include '-DDESTDIR="/usr/local"' -DCHAPMS=1 -DMPPE=1 -DUSE_EAPTLS=1 -DHAS_SHADOW -DHAVE_CRYPT_H=1 -DHAVE_LOGWTMP=1 -I/usr/include/openssl -DHAVE_MULTILINK -DUSE_TDB=1 -DPLUGIN -DPPP_FILTER -DINET6=1 -DMAXOCTETS   -c -o sys-linux.o sys-linux.c
sys-linux.c: In function ‘append_peer_ipv6_address’:
sys-linux.c:2848:20: error: ‘SOL_NETLINK’ undeclared (first use in this function)
     setsockopt(fd, SOL_NETLINK, NETLINK_CAP_ACK, &one, sizeof(one));
                    ^
sys-linux.c:2848:20: note: each undeclared identifier is reported only once for each function it appears in
sys-linux.c:2848:33: error: ‘NETLINK_CAP_ACK’ undeclared (first use in this function)
     setsockopt(fd, SOL_NETLINK, NETLINK_CAP_ACK, &one, sizeof(one));
                                 ^
make[1]: *** [sys-linux.o] Error 1
make[1]: Leaving directory `/root/temp/pppdsource/ppp-2.4.9/pppd'
make: *** [all] Error 2

i need upgrade pppd for rename the pppd connection ( on 2.4.5 is not supported ) .
Could yuo help me ?

**Comment by pali** [comment]
see comment https://github.com/paulusmack/ppp/issues/241#issuecomment-757507518 missing testers for verification...

**Comment by zingaro1972** [comment]
thanks , problem solved !
