### ISSUE TITLE
tty session

### ISSUE THREAD

**Issue by yodelu** [paulusmack/ppp#252]
used 2.4.8 + pptpd 1.4.0 which worked fine
now i'm on 2.4.9 + pptpd 1.4.0 which also works fine but when i do restart or shutdown pc (kde based) i got a liitle gui (that need a confirmation) which tells me that i have an active conection that need to be closed in order to continue...
Any ideea what was dropped in 2.4.9 ?

**Comment by Neustradamus** [comment]
@jjkeijser, @enaess, @Sander80, @lo1ol, @paulusmack: What do you think?

**Comment by enaess** [comment]
What Linux distribution is he using?

**Comment by yodelu** [comment]
pclinuxos (systemV)
Builded packages (2.4.8 and 2.4.9). The packages use the patches provided by fedora
though that maybe some fedora specific causes that then tried mageia ones > the results are the same
right after i initiate a reboot/shutdown a little window apeear on screen which tells me that i have an active tty session which needs to be closed.. 
As a remark that active tty session is a real one ( i'm using it to connect to my  pc win2linux)

**Comment by Sander80** [comment]
No idea. And thank you for the information on the ppp 2.4.9 release.
Installed it, and it perferctly works with my VPN connections.
I am afraid, I cannot help, having zero knowledge about fedora.
I wonder how much time we need to get it into an Ubuntu release.

**Comment by yodelu** [comment]
that is weird almost the same patches on 2.4.8 and 2.4.9 and all of them have nothing to do with my issue (tested different builds)
so i think there's something in the code but .. need to dig 
![Untitled2](https://user-images.githubusercontent.com/79059690/107979412-2f705c80-6fc7-11eb-857f-e29196297b72.png)

**Comment by jjkeijser** [comment]
cannot reproduce it (and am using Fedora 32) so no clue.  Post config files and how you start pppd , that might give a clue.

**Comment by yodelu** [comment]
it does matter the config i have. As i said ppp 2.4.8 worked fine with the same config for 2.4.9
so no matter config (unless a possibly hidden bug in 2.4.8 that was fixed in 2.4.9)
Anyway i have fixed my issue by stopping pppd too when stoping pptpd (this way when pptpd got stopped just make sure no active connections are left behind)  
  stop)
        gprintf "Shutting down pptpd: "
        killproc pptpd
        killproc pppd
        echo
        rm -f /var/lock/subsys/pptpd
        rm -f /var/run/pptpd.pid
        ;;

**Comment by yodelu** [comment]
now i see ppp 2.4.9 uses  /dev/pts/0 instead of /dev/pts/1
on /dev/pts/0  i have a kde session...
Feb 17 21:10:49 localhost pptpd[4444]: CTRL: Client 82.79.214.179 control connection started
Feb 17 21:10:49 localhost pptpd[4444]: CTRL: Starting call (launching pppd, opening GRE)
Feb 17 21:10:49 localhost pppd[4445]: Plugin /usr/lib64/pptpd/pptpd-logwtmp.so loaded.
Feb 17 21:10:49 localhost kernel: PPP generic driver version 2.4.2
Feb 17 21:10:49 localhost pppd[4445]: pppd 2.4.9 started by root, uid 0
Feb 17 21:10:49 localhost pppd[4445]: Using interface ppp0
Feb 17 21:10:49 localhost pppd[4445]: Connect: ppp0 <--> /dev/pts/0


Feb 17 21:20:30 localhost pptpd[5045]: CTRL: Client 82.79.214.179 control connection started
Feb 17 21:20:30 localhost pptpd[5045]: CTRL: Starting call (launching pppd, opening GRE)
Feb 17 21:20:30 localhost pppd[5046]: Plugin /usr/lib64/pptpd/pptpd-logwtmp.so loaded.
Feb 17 21:20:30 localhost kernel: PPP generic driver version 2.4.2
Feb 17 21:20:30 localhost pppd[5046]: pppd 2.4.8 started by root, uid 0
Feb 17 21:20:30 localhost pppd[5046]: Using interface ppp0
Feb 17 21:20:30 localhost pppd[5046]: Connect: ppp0 <--> /dev/pts/1

and 
[root@linux ~]# w
 21:43:38 up 25 min,  3 users,  load average: 0.08, 0.04, 0.07
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
root     :0        21:19   ?xdm?   1:24   0.04s /bin/sh /usr/bin/startkde
root     pts/0     21:19   23:56   0.00s  0.80s kdeinit4: kded4 [kdeinit]
root     pts/2     21:43    0.00s  0.02s  0.00s w

**Comment by jjkeijser** [comment]
>> now i see ppp 2.4.9 uses /dev/pts/0 instead of /dev/pts/1

actually, the pts (tty) is opened and assigned by pptpd (or rather, pptpctrl) and *not by pppd itself; you can check this by starting the connection and then checking the contents of the directory /proc/$PID/fd:

```
lrwx------ 1 root root 64 Feb 18 23:03 0 -> /dev/pts/2
lrwx------ 1 root root 64 Feb 18 23:07 1 -> /dev/pts/2
lrwx------ 1 root root 64 Feb 18 23:07 11 -> /dev/pts/2
lrwx------ 1 root root 64 Feb 18 23:07 12 -> /dev/ppp
lrwx------ 1 root root 64 Feb 18 23:07 13 -> /dev/ppp
```

alternatively you can try to get the debug flag to pptpctrl to work but that seems harder than you'd expect.

**Comment by yodelu** [comment]
finally fixed - in case anyone needs it here is the patch (actually a revert) 
--- a/pppd/Makefile.linux	2021-02-22 20:40:29.265727915 +0200
+++ b/pppd/Makefile.linux	2021-02-22 20:41:55.849735922 +0200
@@ -82,10 +82,8 @@
 # Enable EAP SRP-SHA1 authentication (requires libsrp)
 #USE_SRP=y
 
-# Use libutil; test if logwtmp is declared in <utmp.h> to detect
-ifeq ($(shell echo '\#include <utmp.h>' | $(CC) -E - 2>/dev/null | grep -q logwtmp && echo yes),yes)
+# Use libutil
 USE_LIBUTIL=y
-endif
 
 # Enable EAP-TLS authentication (requires MPPE support, libssl and libcrypto)
 USE_EAPTLS=y
