### ISSUE TITLE
Configuring pppd to accept link-local IPv6 interface id from remote peer

### ISSUE THREAD

**Issue by njh** [paulusmack/ppp#256]
I was originally not sure if this was a bug or if I hadn't found the right configuration option and I have previously asked about this in a couple of places:
* https://unix.stackexchange.com/questions/634033
* https://marc.info/?l=linux-ppp&m=161326467108283

I am now thinking that it is either a bug or a missing feature.

I have two pppd (v2.4.7) instances running, talking to each over over a serial port link. But I can't work out how to get the 'client' pppd to accept the link-local IPv6 interface identifier provided by the 'server' pppd. I am trying to use static addresses so I know the link-local IP address of the remote peer.

On the 'server' I am running:

    pppd file ./ppp-options ipv6 ::1,::2 /dev/ttyAMA0 115200

And on the 'client', I am running:

    pppd file ./ppp-options ipv6cp-accept-local /dev/ttyAMA0 115200

The pppd man page says:

>  ipv6cp-accept-local
>   With this option, pppd will accept the peer's idea of our local IPv6  interface  identifier,
>    **even if the local IPv6 interface identifier was specified in an option**.

But that doesn't seem to be the behaviour I am experiencing.

The client always just uses a locally chosen interface identifier instead. It was suggested to me to try setting the 'client' local interface identifier to all-zero but I have not found a way of doing this through configuration. Or alternatively get the 'server' to Nack the clients choice of interface identifier - but I'm not sure how to achieve that with pppd.

Debug output and `ppp-options` file are in this gist:
https://gist.github.com/njh/ab3282f43c72dcf6932b3693eb7dfca4

Is this a bug, or does there need to be an IPv6 equivalent to 'noipdefault' to use in conjunction with 'ipv6cp-accept-local'?

**Comment by njh** [comment]
Benjamin Cama replied to my linux-ppp email with a patch he created to allow configuring with a zero interface identifier:

https://marc.info/?l=linux-ppp&m=161333836425441&q=p3

> It is a very small change that is basically activated on the "client"-side with:
> 
>  ipv6 ::,

However I have been unable to get it to work - it gets stuck in a negotiation loop.
Here is my debug output:
https://gist.github.com/njh/437713988b108880a8fe23ed10168c0c

**Comment by jjkeijser** [comment]
I'd recommend to try this with ppp v2.4.9, as there were some significant changes to IPv6 support in later releases. 
For example, this
```
  ./pppd file options-pppossh-client-eaptls +ipv6 pty "ssh -t <remotehost> '/usr/sbin/pppd file /home/janjust/ppp/options-pppossh-server-eaptls ipv6 ::100:1,::100:10'"
```
works for me , with the following ppp.log :+1: 

```
rcvd [IPCP ConfReq id=0x1 <addr 172.16.1.1>]
sent [IPCP ConfAck id=0x1 <addr 172.16.1.1>]
rcvd [IPV6CP ConfReq id=0x1 <addr fe80::0000:0000:0100:0001>]
sent [IPV6CP ConfAck id=0x1 <addr fe80::0000:0000:0100:0001>]
rcvd [IPCP ConfRej id=0x1 <compress VJ 0f 01>]
sent [IPCP ConfReq id=0x2 <addr 0.0.0.0>]
rcvd [IPV6CP ConfNak id=0x1 <addr fe80::0000:0000:0100:0010>]
sent [IPV6CP ConfReq id=0x2 <addr fe80::0000:0000:0100:0010>]
rcvd [IPCP ConfNak id=0x2 <addr 172.16.1.10>]
sent [IPCP ConfReq id=0x3 <addr 172.16.1.10>]
rcvd [IPV6CP ConfAck id=0x2 <addr fe80::0000:0000:0100:0010>]
local  LL address fe80::0000:0000:0100:0010
remote LL address fe80::0000:0000:0100:0001
```

**Comment by pali** [comment]
> I was originally not sure if this was a bug ...

Yes, it was a bug and it is already fixed.

> I have two pppd (v2.4.7) instances ...

You have buggy version, upgrade to latest version.

**Comment by njh** [comment]
I had also been testing using the git master branch.
But only on the 'client' - because I had assumed that was where it was going wrong 😞 

After upgrading to version 2.4.9 on the 'server' (the peer that has the interface identifiers configured) it it is working fine! Even with version 2.4.7 running on the 'client'.

Thanks for all the IPv6 improvements you have done @pali 😀

**Comment by pali** [comment]
I still have some unfinished changes for IPv6... but all major IPv6 issues should be fixed in last released version.
