### ISSUE TITLE
pppd：memory leaks occurs when Demand-dial,please conform!

### ISSUE THREAD

**Issue by wuleping** [paulusmack/ppp#27]
pppd , demand.c , demand_conf()  
When it never dials up ok, every demand-dial will apply a memory,but never free.
framemax = PPP_MRU;
framemax += PPP_HDRLEN + PPP_FCSLEN;
 frame = malloc(framemax);

suggestion:
    if (NULL == frame)
    {
        frame = malloc(framemax);
    }

**Comment by paulusmack** [comment]
demand_conf() is only called once at program startup, not every time there is demand for the link, so there is no leak.
