### ISSUE TITLE
PADT on disconnect

### ISSUE THREAD

**Issue by TrueBers** [paulusmack/ppp#3]
Greetings!

As I noticed there is no `PADT` packet sending on termination in `PPPoE` plugin in function `PPPOEDisconnectDevice`.
There is a comment instead: `/* don't send PADT?? */`.

So, I'd like to ask about that. That's very annoying while ISP has high keepalive timeouts (in my case about 5-40 mins of hanging with message `Remote message: % Sessions limit exceeded.`) when one disconnects.

What's the point of not sending it on disconnect? Or maybe I have misunderstood that logic?

Thanks!

**Comment by farnz** [comment]
I've created https://github.com/paulusmack/ppp/pull/34

PADT on clean disconnect is optional according to the RFC; the server is supposed to sense the LCP disconnect and terminate the session.

It sounds like your ISP's PPPoE relay doesn't do that, and instead relies on a long timeout to clean up in the absence of a PPPoE PADT.
