### ISSUE TITLE
diff for files *.c *.h in pppd in order to make the bsd's build  for review

### ISSUE THREAD

**Issue by Hellqvio** [paulusmack/ppp#31]
There are some new files not included in the diffs, but this should be enough ... 

--- /home/ole/ppp-2.4.7/pppd/auth.c Sat Aug  9 14:31:39 2014
+++ auth.c  Sat Dec 27 12:11:07 2014
@@ -81,7 +81,13 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <sys/socket.h>
-#include <utmp.h>
+#ifdef SUPPORT_UTMP
- # include <utmp.h>
  
  +#endif
  +#ifdef SUPPORT_UTMPX
  +#include <utmpx.h>
  +#include <util.h>
  +#endif
  # include <fcntl.h>
  # if defined(_PATH_LASTLOG) && defined(__linux__)
  # include <lastlog.h>
  
  @@ -114,7 +120,9 @@
  # endif
  # include "pathnames.h"
  # include "session.h"
  ## 
  
  +#ifndef PPP_ECP
  +#include "bsd.h"
  +#endif
  static const char rcsid[] = RCSID;
  
  /\* Bits in scan_authfile return value */
  @@ -241,7 +249,9 @@
  
  static char _uafname;      /_ name of most recent +ua file */

+#ifndef **FreeBSD**
 extern char *crypt __P((const char *, const char *));
+#endif

 /\* Prototypes for procedures local to this file. */

@@ -872,6 +882,9 @@
 #ifdef PPP_FILTER
     if (!demand)
        set_filters(&pass_filter, &active_filter);
+
-   /\*    set_filters(&pass_filter_in, &pass_filter_out,
-           &active_filter_in, &active_filter_out); NetBSD      _/
  #endif
     /_ Start CCP and ECP */
     for (i = 0; (protp = protocols[i]) != NULL; ++i)
  @@ -2230,7 +2243,12 @@
      if (ap == NULL)
      novm("authorized addresses");
      ap->word = (char *) (ap + 1);
  +#if 0
-       /\* gcc : warning: strcpy() is almost always misused, please use strlcpy()*/
      strcpy(ap->word, word);
  +#else
- ```
    strlcpy(ap->word, word, strlen(word) + 1);
  ```
  
  +#endif
      *app = ap;
      app = &ap->next;
  }
  --- /home/ole/ppp-2.4.7/pppd/cbcp.c Sat Aug  9 14:31:39 2014
  +++ cbcp.c  Sun Jan  4 15:20:48 2015
  @@ -166,7 +166,7 @@
  
   if (pktlen < CBCP_MINLEN) {
  if (debug)
-       dbglog("CBCP packet is too small");
-       dbglog("CBCP: Packet too short (%d)", pktlen); /*NetBSD patch */
  return;
   }

@@ -176,7 +176,7 @@

```
 if (len > pktlen || len < CBCP_MINLEN) {
if (debug)
```
-       dbglog("CBCP packet: invalid length %d", len);
-       dbglog("CBCP: Invalid packet length (%d/%d)", len, pktlen);/*NetBSD patch */
       return;
   }

@@ -319,7 +319,11 @@
    GETCHAR(type, pckt);
    GETCHAR(opt_len, pckt);
    if (opt_len < 2 || opt_len > len) 
-   {/*NetBSD patch */
-       if (debug)
-       dbglog("CBCP: Malformed option length (%d/%d)", opt_len, len);
      break;
-   }
  
  if (opt_len > 2)
      GETCHAR(delay, pckt);
  --- /home/ole/ppp-2.4.7/pppd/ccp.c  Sat Aug  9 14:31:39 2014
  +++ ccp.c   Sun Jan  4 15:26:08 2015
  @@ -41,7 +41,10 @@
  # ifdef MPPE
  # include "chap_ms.h"   /\* mppe_xxxx_key, mppe_keys_set */
  # include "lcp.h"   /\* lcp_close(), lcp_fsm */
  
  +#ifndef CI_MPPE
  +#include "bsd.h"
  # endif
  
  +#endif
  
  static const char rcsid[] = RCSID;

@@ -679,7 +682,10 @@
    + (go->deflate? CILEN_DEFLATE: 0)
    + (go->predictor_1? CILEN_PREDICTOR_1: 0)
    + (go->predictor_2? CILEN_PREDICTOR_2: 0)
-   + (go->mppe? CILEN_MPPE: 0);
  +#ifdef MPPE
-   + (go->mppe? CILEN_MPPE: 0)
  +#endif
-   ;
  }
  
  /*
  --- /home/ole/ppp-2.4.7/pppd/chap_ms.c  Sat Aug  9 14:31:39 2014
  +++ chap_ms.c   Thu Dec 18 12:29:42 2014
  @@ -397,7 +397,7 @@
  # else
  
  ```
    NULL,
  ```
  # endif
-       our_name, secret, secret_len, response, auth_response,
-       our_name, secret, secret_len, response, private,
      MS_CHAP2_AUTHENTICATEE);
      chapms2_add_to_response_cache(id, challenge, response, auth_response);
  }
  @@ -639,7 +639,7 @@
   /\* LANMan password is case insensitive */
   BZERO(UcasePassword, sizeof(UcasePassword));
   for (i = 0; i < secret_len; i++)
-       UcasePassword[i] = (u_char)toupper(secret[i]);
- ```
    UcasePassword[i] = (u_char)toupper((unsigned char)secret[i]);
  ```
  
   (void) DesSetkey(UcasePassword + 0);
   DesEncrypt( StdText, PasswordHash + 0 );
   (void) DesSetkey(UcasePassword + 7);
  @@ -691,7 +691,8 @@
  
   /\* Convert to ASCII hex string. */
   for (i = 0; i < MAX((MS_AUTH_RESPONSE_LENGTH / 2), sizeof(Digest)); i++)
-   sprintf((char *)&authResponse[i \* 2], "%02X", Digest[i]);
-       snprintf((char *)&authResponse[i \* 2], 
-        MS_AUTH_RESPONSE_LENGTH + 1, "%02X", Digest[i]);
  }

--- /home/ole/ppp-2.4.7/pppd/demand.c   Sat Aug  9 14:31:39 2014
+++ demand.c    Sun Jan  4 15:42:55 2015
@@ -44,7 +44,11 @@
 #include <sys/stat.h>
 #include <sys/socket.h>
 #ifdef PPP_FILTER
+#ifdef IS_BSD
+#include <pcap.h>
+#else
 #include <pcap-bpf.h>
+#endif
 #endif

 #include "pppd.h"
--- /home/ole/ppp-2.4.7/pppd/eap.c  Sat Aug  9 14:31:39 2014
+++ eap.c   Sun Jan  4 16:47:20 2015
@@ -60,6 +60,9 @@
 #include <assert.h>
 #include <errno.h>

+#ifndef PPP_EAP 
+#include "bsd.h"
+#endif
 #include "pppd.h"
 #include "pathnames.h"
 #include "md5.h"
@@ -179,6 +182,21 @@

 /\* Local forward declarations. */
 static void eap_server_timeout __P((void *arg));
+static const char *eap_state_name __P((enum eap_state_code));
+static void eap_client_timeout __P((void *arg));
+static void eap_send_failure __P((eap_state *));
+static void eap_send_success __P((eap_state *));
+static void eap_figure_next_state __P((eap_state *, int));
+static void eap_send_request __P((eap_state *));
+static void eap_rechallenge __P((void *));
+static void srp_lwrechallenge __P((void *));
+static void eap_send_response __P((eap_state *, u_char, u_char, const char *, int));
+static void eap_chap_response __P((eap_state *, u_char, const u_char *, const char *, int));
+static void eap_send_nak __P((eap_state *,u_char,u_char)); 
+static void eap_request __P((eap_state *, u_char *, int, int));
+static void eap_response __P((eap_state *, u_char *, int, int));
+static void eap_success __P((eap_state *, u_char *, int, int));
+static void eap_failure __P((eap_state *, u_char *, int, int));

 /*
- Convert EAP state code to printable string for debug.
  @@ -1043,7 +1061,7 @@
  eap_state _esp;
  u_char id;
  u_char typenum;
  -u_char *str;
  +const char *str;
  int lenstr;
  {
    u_char *outp;
  @@ -1073,8 +1091,8 @@
  eap_chap_response(esp, id, hash, name, namelen)
  eap_state *esp;
  u_char id;
  -u_char *hash;
  -char *name;
  +const u_char *hash;
  +const char *name;
  int namelen;
  {
    u_char *outp;
  @@ -1366,7 +1384,7 @@
          esp->es_usedpseudo = 1;
          /_ Try to get a pseudonym */
          if ((fd = open_pn_file(O_RDONLY)) >= 0) {
  -               strcpy(rhostname, SRP_PSEUDO_ID);
  -               strlcpy(rhostname, SRP_PSEUDO_ID, sizeof(rhostname));
            len = read(fd, rhostname + SRP_PSEUDO_LEN,
                sizeof (rhostname) - SRP_PSEUDO_LEN);
            /\* XXX NAI unsupported */
    --- /home/ole/ppp-2.4.7/pppd/ecp.c  Sat Aug  9 14:31:39 2014
    +++ ecp.c   Sun Jan  4 16:53:51 2015
    @@ -66,6 +66,9 @@
    #include "pppd.h"
    #include "fsm.h"
    #include "ecp.h"
    +#ifndef PPP_ECP
    +#include "bsd.h"
    +#endif
  
  static option_t ecp_option_list[] = {
     { "noecp", o_bool, &ecp_protent.enabled_flag,
  --- /home/ole/ppp-2.4.7/pppd/eui64.c    Sat Aug  9 14:31:39 2014
  +++ eui64.c Thu Dec 18 14:24:29 2014
  @@ -34,6 +34,7 @@
  *
- $Id: eui64.c,v 1.6 2002/12/04 23:03:32 paulus Exp $
  */
  +#ifdef INET6
  # define RCSID  "$Id: eui64.c,v 1.6 2002/12/04 23:03:32 paulus Exp $"

@@ -55,3 +56,4 @@
         e.e8[4], e.e8[5], e.e8[6], e.e8[7]);
     return buf;
 }
+#endif /_inet6_/
--- /home/ole/ppp-2.4.7/pppd/fsm.c  Sat Aug  9 14:31:39 2014
+++ fsm.c   Sun Jan  4 17:01:40 2015
@@ -65,6 +65,7 @@
 static void fsm_rtermack __P((fsm *));
 static void fsm_rcoderej __P((fsm *, u_char *, int));
 static void fsm_sconfreq __P((fsm *, int));
+static void terminate_layer __P((fsm *, int));

 #define PROTO_NAME(f)  ((f)->callbacks->proto_name)

@@ -306,7 +307,7 @@
     case ACKRCVD:
     case ACKSENT:
    if (f->retransmits <= 0) {
-       warn("%s: timeout sending Config-Requests\n", PROTO_NAME(f));
- ```
    warn("%s: timeout sending Config-Requests", PROTO_NAME(f));/*netbsd hack*/
  f->state = STOPPED;
  if( (f->flags & OPT_PASSIVE) == 0 && f->callbacks->finished )
  (*f->callbacks->finished)(f);
  ```
  
  --- /home/ole/ppp-2.4.7/pppd/ipcp.c Sat Aug  9 14:31:39 2014
  +++ ipcp.c  Sun Jan  4 17:07:43 2015
  @@ -1873,12 +1873,12 @@
      }
  
  ```
  /* assign a default route through the interface if required */
  ```
-       if (ipcp_wantoptions[f->unit].default_route) 
- ```
    if (ho->hisaddr != 0 && ipcp_wantoptions[f->unit].default_route) /*nb hack*/
  if (sifdefaultroute(f->unit, go->ouraddr, ho->hisaddr))
      default_route_set[f->unit] = 1;
  
  /* Make a proxy ARP entry if requested. */
  ```
-       if (ho->hisaddr != 0 && ipcp_wantoptions[f->unit].proxy_arp)
-       if (ipcp_wantoptions[f->unit].proxy_arp)/_nb hack_/
      if (sifproxyarp(f->unit, ho->hisaddr))
          proxy_arp_set[f->unit] = 1;

--- /home/ole/ppp-2.4.7/pppd/ipv6cp.c   Sat Aug  9 14:31:39 2014
+++ ipv6cp.c    Sun Jan  4 17:19:24 2015
@@ -137,6 +137,7 @@
  *
- $Id: ipv6cp.c,v 1.21 2005/08/25 23:59:34 paulus Exp $ 
  */
  +#ifdef INET6
  # define RCSID  "$Id: ipv6cp.c,v 1.21 2005/08/25 23:59:34 paulus Exp $"

@@ -203,6 +204,7 @@
 static void ipv6cp_up __P((fsm _));        /_ We're UP _/
 static void ipv6cp_down __P((fsm *));      /_ We're DOWN _/
 static void ipv6cp_finished __P((fsm *));  /_ Don't need lower layer */
+static char *llv6_ntoa __P((eui64_t));

 fsm ipv6cp_fsm[NUM_PPP];       /\* IPV6CP fsm structure */

@@ -337,6 +339,9 @@
     struct in6_addr addr;
     static int prio_local, prio_remote;

+#ifndef s6_addr32
+#define s6_addr32 __u6_addr.__u6_addr32 /\* non-standard */
+#endif
 #define VALIDID(a) ( (((a).s6_addr32[0] == 0) && ((a).s6_addr32[1] == 0)) && \
            (((a).s6_addr32[2] != 0) || ((a).s6_addr32[3] != 0)) )

@@ -384,8 +389,6 @@
     return 1;
 }
## -char *llv6_ntoa(eui64_t ifaceid);

 static void
 printifaceid(opt, printer, arg)
     option_t _opt;
@@ -404,13 +407,13 @@
 /_
- Make a string representation of a network address.
  */
  -char *
  +static char *
  llv6_ntoa(ifaceid)
     eui64_t ifaceid;
  {
     static char b[64];
-    sprintf(b, "fe80::%s", eui64_ntoa(ifaceid));
-    snprintf(b, sizeof(b), "fe80::%s", eui64_ntoa(ifaceid));
   return b;
  }

@@ -1388,9 +1391,10 @@
     char strspeed[32], strlocal[32], strremote[32];
     char *argv[8];
-    sprintf(strspeed, "%d", baud_rate);
-    strcpy(strlocal, llv6_ntoa(ipv6cp_gotoptions[0].ourid));
-    strcpy(strremote, llv6_ntoa(ipv6cp_hisoptions[0].hisid));
-    snprintf(strspeed, sizeof(strspeed), "%d", baud_rate);
-    strlcpy(strlocal, llv6_ntoa(ipv6cp_gotoptions[0].ourid), sizeof(strlocal));
-    strlcpy(strremote, llv6_ntoa(ipv6cp_hisoptions[0].hisid),
- ```
   sizeof(strremote));
  ```
  
   argv[0] = script;
   argv[1] = ifname;
  @@ -1542,3 +1546,4 @@
  return 0;
   return 1;
  }
  +#endif /_INET6_/
  --- /home/ole/ppp-2.4.7/pppd/lcp.c  Sat Aug  9 14:31:39 2014
  +++ lcp.c   Sun Jan  4 17:27:24 2015
  @@ -55,6 +55,9 @@
  # include "lcp.h"
  # include "chap-new.h"
  # include "magic.h"
  
  +#ifndef PPP_EAP
  +#include "bsd.h"
  +#endif
  
  static const char rcsid[] = RCSID;

--- /home/ole/ppp-2.4.7/pppd/main.c Fri Jan  2 18:37:46 2015
+++ main.c  Fri Jan  2 18:38:45 2015
@@ -91,6 +91,10 @@
 #include <netinet/in.h>
 #include <arpa/inet.h>

+#ifndef PPP_EAP
+#include "bsd.h"
+#endif
+
 #include "pppd.h"
 #include "magic.h"
 #include "fsm.h"
@@ -1589,7 +1593,7 @@
        dup2(infd, 0);
    if (outfd != 1)
        dup2(outfd, 1);
-   if (errfd != 2)
-   if (errfd != 2 && errfd != -1) /\* patch from NetBSD, make sense? */ 
      dup2(errfd, 2);
  
  if (log_to_fd > 2)
  @@ -1604,7 +1608,8 @@
      close(infd);
  if (outfd != 1)
      close(outfd);
-   if (errfd != 2)
-   if (errfd != 2 && errfd != -1) /\* patch from NetBSD, make sense? 
-   should errfd be keept "open" if < 0 ?. the return value of closed is not checked annyway */
      close(errfd);
  
  notify(fork_notifier, 0);
  @@ -1684,7 +1689,7 @@
   ++conn_running;
   pid = safe_fork(in, out, errfd);
-    if (pid != 0 && log_to_fd < 0)
-    if (pid != 0 && log_to_fd < 0 && errfd >= 0)/\* patch from NetBSD, make sense? */
  close(errfd);
  
   if (pid < 0) {
  @@ -1825,7 +1830,7 @@
   setuid(0);     /\* set real UID = root */
   setgid(getegid());

-#ifdef BSD
+#ifdef IS_BSD
     /\* Force the priority back to zero if pppd is running higher. _/
     if (setpriority (PRIO_PROCESS, 0, 0) < 0)
    warn("can't reset priority to 0: %m");
--- /home/ole/ppp-2.4.7/pppd/md4.c  Sat Aug  9 14:31:39 2014
+++ md4.c   Mon Dec  2 09:25:58 2013
@@ -30,6 +30,8 @@
 /_ Implementation notes:
 *\* This implementation assumes that ints are 32-bit quantities.
 */
+#ifndef **NetBSD**
+#ifdef CHAPMS

 #define TRUE  1
 #define FALSE 0
@@ -293,7 +295,8 @@
     }
   }
##  }

+#endif
+#endif /\* netbsd_/
 /_
 *\* End of md4.c
 ***************************_(cut)**_********************************/
--- /home/ole/ppp-2.4.7/pppd/multilink.c    Sat Aug  9 14:31:39 2014
+++ multilink.c Sun Jan  4 17:48:32 2015
@@ -27,6 +27,8 @@
- AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
- OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  _/
  +
  +#ifdef HAVE_MULTILINK
  #include <string.h>
  #include <ctype.h>
  #include <stdlib.h>
  @@ -573,7 +575,7 @@
      if (_str == 0)
          break;
      if (p <= str)
  -           for (p = str; isxdigit(*p); ++p)
  -           for (p = str; isxdigit((unsigned char)*p); ++p)
            ;
    i = p - str;
    if (i == 0)
    @@ -590,3 +592,4 @@
    return 1;
    }

+#endif /_HAVE_MULTILINK_/
--- /home/ole/ppp-2.4.7/pppd/options.c  Sat Aug  9 14:31:39 2014
+++ options.c   Sun Jan  4 17:56:59 2015
@@ -84,7 +84,7 @@
 struct option_value {
     struct option_value *next;
     const char *source;
-    char value[1];
-    char value[255];
  };
  
  /*
  @@ -346,7 +346,7 @@
  # define IMPLEMENTATION ""
  # endif

-static char *usage_string = "\
+static const char *usage_string = "\
 pppd version %s\n\
 Usage: %s [ options ], where options are:\n\
    <device>    Communicate over the named device\n\
@@ -591,17 +591,17 @@
  */
 static int
 match_option(name, opt, dowild)
-    char *name;
-    const char *name;
   option_t *opt;
   int dowild;
  {
-   int (_match) __P((char *, char *_, int));
-   int (_match) __P((const char *, char *_, int));
  
  if (dowild != (opt->type == o_wild))
      return 0;
  if (!dowild)
      return strcmp(name, opt->name) == 0;
-   match = (int (_) __P((char *, char *_, int))) opt->addr;
-   match = (int (_) __P((const char *, char *_, int))) opt->addr;
  return (*match)(name, NULL, 0);
  }

@@ -793,11 +793,11 @@
    if (!(*parser)(argv))
        return 0;
    if (opt->flags & OPT_A2LIST) {
## \-       struct option_value *ovp, *pp;
-       ovp = malloc(sizeof(_ovp) + strlen(_argv));
-       if (ovp != 0) {
-       strcpy(ovp->value, *argv);
-       struct option_value ov;
-       struct option_value *ovp= &ov;
-       struct option_value *pp;
-       if (ovp != NULL) {
-       strlcpy(ovp->value, *argv, sizeof(ovp->value));
      ovp->source = option_source;
      ovp->next = NULL;
      if (opt->addr2 == NULL) {
  @@ -1654,7 +1654,8 @@
  {
     char *arg = argv[0];
     char *eqp;
-    struct userenv _uep, *_insp;
-    struct userenv ue;
-    struct userenv _uep = NULL, *_insp;
  
   if ((eqp = strchr(arg, '=')) == NULL) {
      option_error("missing = in name=value: %s", arg);
  @@ -1675,9 +1676,11 @@
  return 1;
   /\* The name never changes, so allocate it with the structure */
   if (uep == NULL) {
-   uep = malloc(sizeof (*uep) + (eqp-arg));
-   strncpy(uep->ue_name, arg, eqp-arg);
-   uep->ue_name[eqp-arg] = '\0';
-   uep = &ue;
-   strlcpy(uep->ue_name, arg,sizeof(uep->ue_name));
-      // uep = malloc(sizeof (*uep) + (eqp-arg));
-      // strncpy(uep->ue_name, arg, eqp-arg);
-       //uep->ue_name[eqp-arg] = '\0';
      uep->ue_next = NULL;
      insp = &userenv_list;
      while (*insp != NULL)
  @@ -1691,7 +1694,6 @@
  }
  if (uep2 == NULL && !uep->ue_isset)
      find_option("unset")->flags |= OPT_NOPRINT;
-   free(uep->ue_value);
     }
   uep->ue_isset = 1;
   uep->ue_priv = privileged_option;
  @@ -1728,6 +1730,7 @@
  user_unsetenv(argv)
     char **argv;
  {
-    struct userenv ue;
   struct userenv _uep, *_insp;
   char *arg = argv[0];

@@ -1748,8 +1751,8 @@
    return 1;
     /\* The name never changes, so allocate it with the structure */
     if (uep == NULL) {
-   uep = malloc(sizeof (*uep) + strlen(arg));
-   strcpy(uep->ue_name, arg);
-   uep = &ue;
-   strlcpy(uep->ue_name, arg,sizeof(uep->ue_name));
  uep->ue_next = NULL;
  insp = &userenv_list;
  while (*insp != NULL)
  @@ -1763,7 +1766,6 @@
  }
  if (uep2 == NULL && uep->ue_isset)
      find_option("set")->flags |= OPT_NOPRINT;
-   free(uep->ue_value);
   }
   uep->ue_isset = 0;
   uep->ue_priv = privileged_option;
  --- /home/ole/ppp-2.4.7/pppd/pppcrypt.c Sun Jan  4 18:15:08 2015
  +++ pppcrypt.c  Sat Dec 20 06:45:51 2014
  @@ -31,8 +31,14 @@
  */
  # include <errno.h>
  
  +#include <stdlib.h>
  +#include <unistd.h>
  # include "pppd.h"
  # include "pppcrypt.h"
  
  +
  +static u_char Get7Bits(u_char *, int);
  +static void MakeKey(u_char *, u_char *);
  +
  static u_char
  Get7Bits(input, startBit)
  u_char *input;
  @@ -68,6 +74,9 @@
  }
  # ifdef USE_CRYPT
  
  +static void Expand(u_char _, u_char *);
  +static void Collapse(u_char *, u_char *);
  +
  /_
  - in == 8-byte string (expanded version of the 56-bit key)
  - out == 64-byte string where each byte is either 1 or 0
    @@ -170,7 +179,7 @@
    }
  
  bool
  -DesEncrypt(clear, key, cipher)
  +DesEncrypt(clear, cipher)
  u_char _clear; /_ IN  8 octets _/
  u_char *cipher;    /_ OUT 8 octets */
  {
  --- /home/ole/ppp-2.4.7/pppd/session.c  Sat Aug  9 14:31:39 2014
  +++ session.c   Sun Jan  4 18:33:45 2015
  @@ -72,11 +72,16 @@
  # include <stdlib.h>
  # include <string.h>
  # include <pwd.h>
  
  +#ifndef USE_CRYPT
  # include <crypt.h>
  
  +#endif
  # ifdef HAS_SHADOW
  # include <shadow.h>
  # endif
  # include <time.h>
  
  +#ifndef _SYS_STDINT_H_
  +#include <stdint.h> 
  +#endif
  # include <utmp.h>
  # include <fcntl.h>
  # include <unistd.h>
  
  --- /home/ole/ppp-2.4.7/pppd/utils.c    Sat Aug  9 14:31:39 2014
  +++ utils.c Sun Jan  4 19:56:51 2015
  @@ -41,7 +41,6 @@
  # include <syslog.h>
  # include <netdb.h>
  # include <time.h>
  
  -#include <utmp.h>
  # include <pwd.h>
  # include <sys/param.h>
  # include <sys/types.h>
  
  @@ -75,6 +74,7 @@
   int len;
  };

+#ifndef __BSD_VISIBLE
 /*
- strlcpy - like strcpy/strncpy, doesn't overflow destination buffer,
- always leaves destination null-terminated (for len > 0).
  @@ -112,6 +112,7 @@
  
   return dlen + strlcpy(dest + dlen, src, (len > dlen? len - dlen: 0));
  }
  +#endif
  
  /*
  @@ -196,7 +197,7 @@
      width = va_arg(args, int);
      c = *++fmt;
  } else {
  -       while (isdigit(c)) {
  -       while (isdigit((unsigned char)c)) {
    width = width \* 10 + c - '0';
    c = *++fmt;
    }
    @@ -208,7 +209,7 @@
    c = *++fmt;
    } else {
    prec = 0;
  -       while (isdigit(c)) {
  -       while (isdigit((unsigned char)c)) {
        prec = prec \* 10 + c - '0';
        c = *++fmt;
    }
    @@ -288,9 +289,12 @@
    break;
    case 't':
    time(&t);
  -       str = ctime(&t);
  -       if ((str = ctime(&t)) == NULL)
  -           strlcpy(str = num, "?", sizeof(num));
  -       else {
        str += 4;       /\* chop off the day name _/
        str[15] = 0;    /_ chop off year and newline */
  -       }
    break;
    case 'v':       /\* "visible" string _/
    case 'q':       /_ quoted string _/
    --- /home/ole/ppp-2.4.7/pppd/md4.h  Sat Aug  9 14:31:39 2014
    +++ md4.h   Thu Dec 18 12:16:10 2014
    @@ -1,4 +1,3 @@
    -
    /_
    *\* ********************************************************************
    *\* md4.h -- Header file for implementation of                        **
    @@ -7,7 +6,9 @@
    *\* (C) 1990 RSA Data Security, Inc.                                  **
    *\* ********************************************************************
    */
    -
    +#ifdef **NetBSD**
    +#include <md4.h>
    +#else
    #ifndef **P
    # if defined(__STDC**) || defined(**GNUC**)
    #  define __P(x) x
    @@ -59,6 +60,7 @@
    */
    extern void MD4Final __P((unsigned char *, MD4_CTX *));

+#endif /\* **NetBSD**_/
 /_
 *\* End of md4.h
 ***************************_(cut)**_********************************/
--- /home/ole/ppp-2.4.7/pppd/md5.h  Sat Aug  9 14:31:39 2014
+++ md5.h   Thu Dec 18 12:46:14 2014
@@ -37,6 +37,14 @@

---

  */

+#ifdef HAVE_MD5
+#include <md5.h>
+#define MD5_Init(x)        MD5Init(x)
+#define MD5_Update(x, y, z)    MD5Update(x, y, z)
+#define MD5_Final(x, y)        MD5Final(x, y)
+#define **MD5_INCLUDE**
+#endif
+
 #ifndef **MD5_INCLUDE**

 /\* typedef a 32-bit type */
--- /home/ole/ppp-2.4.7/pppd/pppcrypt.h Sat Aug  9 14:31:39 2014
+++ pppcrypt.h  Sat Dec 20 06:41:29 2014
@@ -38,7 +38,11 @@
 #endif

 #ifndef USE_CRYPT
+#ifdef **FreeBSD**
+#include <openssl/des.h>
+#else
 #include <des.h>
+#endif
 #endif

 extern bool    DesSetkey __P((u_char *));
--- /home/ole/ppp-2.4.7/pppd/pppd.h Sat Aug  9 14:31:39 2014
+++ pppd.h  Sun Jan  4 18:25:33 2015
@@ -71,6 +71,10 @@
 #include "eui64.h"
 #endif

+#ifndef    _STDBOOL_H_
+#include <stdbool.h>       /\* for bool _/
+#endif
+
 /_
- Limits.
  */
  @@ -85,8 +89,6 @@
- Option descriptor structure.
  */
## -typedef unsigned char  bool;

 enum opt_type {
    o_special_noarg = 0,
    o_special = 1,
@@ -214,7 +216,7 @@
 extern int hungup;     /\* Physical layer has disconnected _/
 extern int ifunit;     /_ Interface unit number _/
 extern char    ifname[];   /_ Interface name _/
-extern char    hostname[]; /_ Our hostname _/
+extern char    hostname[MAXNAMELEN];   /_ Our hostname _/
 extern u_char  outpacket_buf[]; /_ Buffer for outgoing packets _/
 extern int devfd;      /_ fd of underlying device _/
 extern int fd_ppp;     /_ fd for talking PPP _/
@@ -474,7 +476,7 @@
    bool ue_isset;      /_ 1 for set, 0 for unset _/
    bool ue_priv;       /_ from privileged source _/
    const char *ue_source;  /_ source name */
-   char ue_name[1];    /\* variable name */
- ```
    char ue_name[255];        /* variable name */
  ```
  
  };
  
  extern struct userenv _userenv_list;
  @@ -527,8 +529,10 @@
                              /_ Format a string for output _/
  int slprintf __P((char *, int, char *, ...));      /_ sprintf++ _/
  int vslprintf __P((char *, int, char *, va_list)); /_ vsprintf++ _/
  +#ifndef __BSD_VISIBLE
  size_t strlcpy __P((char *, const char *, size_t));    /_ safe strcpy _/
  size_t strlcat __P((char *, const char *, size_t));    /_ safe strncpy _/
  +#endif
  void dbglog __P((char *, ...));    /_ log a debug message _/
  void info __P((char *, ...));  /_ log an informational message _/
  void notice __P((char *, ...));    /_ log a notice-level message _/
  @@ -736,6 +740,10 @@
  extern void (_ip_choose_hook) __P((u_int32_t _));
  extern void (_ipv6_up_hook) __P((void));
  extern void (_ipv6_down_hook) __P((void));
  +void (_lcp_up_hook) __P((void));
  +void (_lcp_down_hook) __P((void));
  +void (_lcp_echo_hook) __P((int));
  +void (*lcp_echoreply_hook) __P((int));
  
  extern int (_chap_check_hook) __P((void));
  extern int (_chap_passwd_hook) __P((char _user, char *passwd));
  --- /home/ole/ppp-2.4.7/pppd/sha1.h Sat Aug  9 14:31:39 2014
  +++ sha1.h  Sun Jan  4 18:42:58 2015
  @@ -1,13 +1,20 @@
  /_ sha1.h */

+#if (defined **OpenBSD**) || (defined **NetBSD**)
+#include <sha1.h>
+#define SHA1_Init(x)       SHA1Init(x)
+#define SHA1_Update(x, y, z)   SHA1Update(x, y, z)
+#define SHA1_Final(x, y)   SHA1Final(x, y)
+#define __SHA1_INCLUDE_
+#endif
 /\* If OpenSSL is in use, then use that version of SHA-1 */
+#ifndef __SHA1_INCLUDE_
 #ifdef OPENSSL
 #include <t_sha.h>
 #define __SHA1_INCLUDE_
 #endif
+#endif
## -#ifndef __SHA1_INCLUDE_

 #ifndef SHA1_SIGNATURE_SIZE
 #ifdef SHA_DIGESTSIZE
 #define SHA1_SIGNATURE_SIZE SHA_DIGESTSIZE
@@ -16,6 +23,7 @@
 #endif
 #endif

+#ifndef __SHA1_INCLUDE_
 typedef struct {
     u_int32_t state[5];
     u_int32_t count[2];

**Comment by paulusmack** [comment]
Wow, github really mangled that diff...
