### ISSUE TITLE
install mppe.h header

### ISSUE THREAD

**Issue by clintonroy** [paulusmack/ppp#35]
make install-devel does not install mppe.h, which can be included by chap_ms.h.

**Comment by clintonroy** [comment]
The following patch works for me:

diff -rupN ppp-2.4.5.orig/pppd/Makefile.linux ppp-2.4.5/pppd/Makefile.linux
--- ppp-2.4.5.orig/pppd/Makefile.linux  2009-11-17 08:26:07.000000000 +1000
+++ ppp-2.4.5/pppd/Makefile.linux       2015-03-02 14:37:03.072515408 +1000
@@ -85,7 +85,7 @@ ifdef CHAPMS
 CFLAGS   += -DCHAPMS=1
 NEEDDES=y
 PPPDOBJS += md4.o chap_ms.o
-HEADERS        += md4.h chap_ms.h
+HEADERS        += md4.h chap_ms.h mppe.h
 ifdef MSLANMAN
 CFLAGS   += -DMSLANMAN=1
 endif

**Comment by paulusmack** [comment]
I just committed a slightly different fix for this (HEADERS += mmpe.h inside the ifdef MPPE block).
