### ISSUE TITLE
ftp seems to be down

### ISSUE THREAD

**Issue by Ploppz** [paulusmack/ppp#36]
Hi, the ftp url given on the home page seems to be down (ftp://ftp.samba.org/pub/ppp/). Resulting in the package ppp-mppe from AUR failing to install. Don't know if it's ok to post this here.

**Comment by bjacke** [comment]
please just use this URL: https://download.samba.org/pub/ppp/
ftp is no longer an option on the server and also the webserver is https only since a while now.

**Comment by bpringlemeir** [comment]
I figured this out by guessing.  However, updating the https://ppp.samba.org/download.html page to not have 'FTP' and to point to the 'https' link would be helpful?

**Comment by paulusmack** [comment]
I updated the web page as suggested.
