### ISSUE TITLE
"replacedefaultroute" fails in ipv6 session

### ISSUE THREAD

**Issue by rogers0** [paulusmack/ppp#40]
I found the default ipv6 route won't be set when configured with "replacedefaultroute" and "+ipv6" options.

I also find there was a [Debian bug #477245](https://bugs.debian.org/477245) on the same issue before, and is said to be forwarded to the formal [BTS#2126](http://ppp.samba.org/cgi-bin/ppp-bugs/incoming?id=2126), but I cannot find it in github's new issue list. So here I create a new report.

There's a script fix on [Debian bug #477245](https://bugs.debian.org/477245), so you can fix this issue by:

a) simply merge that script into ipv6-up.d/ directory, or
b) implement the similar code inside ppp

Looking forward to a solution for basic ipv6 pppoe.
Thank you!

**Comment by rogers0** [comment]
Submitted a [pull request] (https://github.com/paulusmack/ppp/pull/41) to fix this issue.

**Comment by madhatter0** [comment]
See also [this pull request](https://github.com/paulusmack/ppp/pull/77), which refers to your request but implements a new option inside `pppd` instead of outsourcing it to a script.

**Comment by paulusmack** [comment]
Fix merged

**Comment by Neustradamus** [comment]
@rogers0: It works correctly now with https://github.com/paulusmack/ppp/pull/77?
