### ISSUE TITLE
When using linkname, sometimes pid cache file contains only pid number

### ISSUE THREAD

**Issue by EddyDz** [paulusmack/ppp#44]
Note: this could be specific to my distro, I am using Debian "Wheezy" on a BeagleBone Black (OMAP).

For the most part, using "linkname modem0" works by creating the file /var/run/ppp-modem0.pid and this file contains 2 lines of text. Line 1 has the pid number and line 2 has the interface name ("ppp0"). On rare occasions this file is created with only the pid number of the process. I treat this as an error in my PPP manager and react accordingly.

Is the occasional absence of the interface name (line 2) part of the normal operation of pppd, or is this some bug in the program? 
- Richard

--- example logs, from my PPP manager ----

LS Log showing the PID cache issue occuring;

Oct  3 20:07:28 [000033] [20:07:28] PPPD: {pppHandler::StartDaemon} - examining /var/run/ppp-modem0.pid for process id and basic number...
Oct  3 20:07:28 [000033] [20:07:28] PPPD: {pppHandler::StartDaemon} - PID[2309], Basic Intf. Num[]
Oct  3 20:07:28 [000033] [20:07:28] PPPD: {pppHandler::StartDaemon} - error, pppd startup confirmation (pid-cache data) failed!

Note: "Basic Intf. Num[] is blank.

This segment (below) shows correct parsing of the pid cache;

Oct  2 00:08:53 [000033] [00:08:53] PPPD: {pppHandler::StartDaemon} - examining /var/run/ppp-modem0.pid for process id and basic number...
Oct  2 00:08:53 [000033] [00:08:53] PPPD: {pppHandler::StartDaemon} - PID[2289], Basic Intf. Num[ppp0]
Oct  2 00:08:53 [000033] [00:08:53] NET : {PPPIntf::NetUp} - <<PPP UP>>

**Comment by EddyDz** [comment]
Additional;

pppd version: 2.4.5

**Comment by paulusmack** [comment]
pppd writes the file more than once, initially with just the pid, and then once the PPP interface is created, with the pid and the name of the interface.
