### ISSUE TITLE
PPPoE MTU problem

### ISSUE THREAD

**Issue by wenzhuoz** [paulusmack/ppp#48]
The PPPoE Access Concentrator of my ISP offers MRU values of both 1492 and 1442. ppp-2.4.5 in Ubuntu 14.04 adopts 1492 as the MTU of the ppp device, while ppp-2.4.7 in Ubuntu 16.04 (xenial developement) adopts 1442. Choosing the lower MTU on the WAN link (ppp0) exposes users to the nasty PMTU-D problem, especially for remote VPN clients. I also reproduced the same problem in openwrt 15.05 and dd-wrt r29085, both of which come with ppp-2.4.7.

ppp-2.4.5 (Ubuntu 14.04):

> Feb 19 17:24:42 micky pppd[5479]: sent [LCP ConfReq id=0x1 <mru 1492> <magic 0x83ccc32e>]
> Feb 19 17:24:42 micky pppd[5479]: rcvd [LCP ConfAck id=0x1 <mru 1492> <magic 0x83ccc32e>]
> Feb 19 17:24:45 micky pppd[5479]: rcvd [LCP ConfReq id=0x2 <mru 1492> <auth pap> <magic 0xf96f421e>]
> Feb 19 17:24:45 micky pppd[5479]: sent [LCP ConfAck id=0x2 <mru 1492> <auth pap> <magic 0xf96f421e>]
> Feb 19 17:24:45 micky pppd[5479]: sent [LCP EchoReq id=0x0 magic=0x83ccc32e]
> Feb 19 17:24:45 micky pppd[5479]: sent [PAP AuthReq id=0x1 user="<username>" password=<hidden>]
> Feb 19 17:24:45 micky pppd[5479]: rcvd [LCP EchoRep id=0x0 magic=0xf96f421e]
> Feb 19 17:24:46 micky pppd[5479]: rcvd [LCP ConfReq id=0x8d <mru 1442> <auth pap> <magic 0x457aa88f>]
> Feb 19 17:24:46 micky pppd[5479]: sent [LCP ConfReq id=0x2 <mru 1492> <magic 0x2cd5dabd>]
> Feb 19 17:24:46 micky pppd[5479]: sent [LCP ConfAck id=0x8d <mru 1442> <auth pap> <magic 0x457aa88f>]
> Feb 19 17:24:46 micky pppd[5479]: rcvd [LCP ConfAck id=0x2 <mru 1492> <magic 0x2cd5dabd>]
> Feb 19 17:24:46 micky pppd[5479]: sent [LCP EchoReq id=0x0 magic=0x2cd5dabd]
> Feb 19 17:24:46 micky pppd[5479]: sent [PAP AuthReq id=0x2 user="<username>" password=<hidden>]
> Feb 19 17:24:46 micky pppd[5479]: rcvd [LCP EchoRep id=0x0 magic=0x457aa88f]
> Feb 19 17:24:46 micky pppd[5479]: rcvd [PAP AuthAck id=0x2 ""]
> Feb 19 17:24:46 micky pppd[5479]: PAP authentication succeeded

ppp-2.4.7 (Ubuntu xenial development):

> Feb 20 08:45:20 micky pppd[3837]: sent [LCP ConfReq id=0x1 <mru 1492> <magic 0xee104411>]
> Feb 20 08:45:20 micky pppd[3837]: rcvd [LCP ConfAck id=0x1 <mru 1492> <magic 0xee104411>]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [LCP ConfReq id=0x2 <mru 1492> <auth pap> <magic 0xff9adf45>]
> Feb 20 08:45:23 micky pppd[3837]: sent [LCP ConfAck id=0x2 <mru 1492> <auth pap> <magic 0xff9adf45>]
> Feb 20 08:45:23 micky pppd[3837]: sent [LCP EchoReq id=0x0 magic=0xee104411]
> Feb 20 08:45:23 micky pppd[3837]: sent [PAP AuthReq id=0x1 user="<username>" password=<hidden>]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [LCP EchoRep id=0x0 magic=0xff9adf45]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [LCP ConfReq id=0xa1 <mru 1442> <auth pap> <magic 0x316220a6>]
> Feb 20 08:45:23 micky pppd[3837]: sent [LCP ConfReq id=0x2 <mru 1492> <magic 0xbca3ad64>]
> Feb 20 08:45:23 micky pppd[3837]: sent [LCP ConfAck id=0xa1 <mru 1442> <auth pap> <magic 0x316220a6>]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [LCP ConfAck id=0x2 <mru 1492> <magic 0xbca3ad64>]
> Feb 20 08:45:23 micky pppd[3837]: sent [LCP EchoReq id=0x0 magic=0xbca3ad64]
> Feb 20 08:45:23 micky pppd[3837]: sent [PAP AuthReq id=0x2 user="<username>" password=<hidden>]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [LCP EchoRep id=0x0 magic=0x316220a6]
> Feb 20 08:45:23 micky pppd[3837]: rcvd [PAP AuthAck id=0x2 ""]
> Feb 20 08:45:23 micky pppd[3837]: PAP authentication succeeded

See https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1547754 and http://svn.dd-wrt.com/ticket/5221 for more detailed information.

**Comment by wenzhuoz** [comment]
Based on [The Point-to-Point Protocol (PPP), 6.1. Maximum-Receive-Unit (MRU)](https://tools.ietf.org/html/rfc1661#page-41) ​and [A Method for Transmitting PPP Over Ethernet (PPPoE), 7. LCP Considerations](https://tools.ietf.org/html/rfc2516#page-7), I think pppd should choose the larger MRU as the MTU of ppp devices.

**Comment by nihilus** [comment]
Nah, it shouldn't. You don't have a different MRU than your MTU on ethernet.

However you should do MSS clamping if you want to route packets via the connection.

**Comment by paulusmack** [comment]
This is not something that should be solved in pppd.
