### ISSUE TITLE
MUSL build breakage

### ISSUE THREAD

**Issue by yegorich** [paulusmack/ppp#51]
Following patch [1] fixes the issue. Though it might be better to divide this patch in logical chunks. 

[1] http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-connectivity/ppp/ppp/0001-Fix-build-with-musl.patch

**Comment by mjeveritt** [comment]
@Polynomial-C this was one of the options I spoke about.
In ::musl overlay we have [this](https://gitweb.gentoo.org/proj/musl.git/tree/net-dialup/ppp/files/ppp-2.4.7-musl.patch)

**Comment by RICCIARDI-Adrien** [comment]
Hi,
This issue might be closed now that musl support has been merged (see 7555728c50db87ae7d5b8c018c006a14bf374584).

**Comment by Neustradamus** [comment]
@yegorich, @mjeveritt, @Polynomial-C, @RICCIARDI-Adrien: Have you tested, perfect for you?

Linked to:
- https://github.com/paulusmack/ppp/issues/73
- https://github.com/paulusmack/ppp/pull/110
- https://github.com/paulusmack/ppp/commit/7555728c50db87ae7d5b8c018c006a14bf374584

**Comment by mjeveritt** [comment]
See https://github.com/paulusmack/ppp/issues/73#issuecomment-753160578
