### ISSUE TITLE
3g dial AT char ^

### ISSUE THREAD

**Issue by shi-hao** [paulusmack/ppp#56]
i want to send at command to set the 3g module's network mode, the command is as follow.
AT^PREFMODE=8
but the char ^ is not sent atually, so i want to know how to send the char ^, how to edit the chat script.

**Comment by paulusmack** [comment]
Put a backslash before the ^, like this: AT\^PREFMODE=8

**Comment by paulusmack** [comment]
try again: AT\\^PREFMODE=8

**Comment by shi-hao** [comment]
thank you  paulusmack， thank you very much！
The day before yesterday, i comment several lines source code about the char ^, then compile,
it also works. But i know it is not a reasonable way, thank you!
