### ISSUE TITLE
Add tags for old releases

### ISSUE THREAD

**Issue by cognifloyd** [paulusmack/ppp#68]
Please add tags to the following commits:
- [ ] 2.0.1 0b63a24d54ba4708c88e31bdd74b0145956c1478 (oldest commit in repo)
- [ ] 2.0.2 827c2e429c211f4d28b8e9131e44f1289f121e45
- [ ] 2.1.0 08d8e50ecd9e7188b8c9781bd37b3f48009ca524
- [ ] 2.1.1 f7376b4e878809e41784938852db07f188455196
- [x] 2.1.2a 70a369c133fa23289034f738bb50bde5df23db37
- [ ] 2.1.2 01348355a72c10aeb6f9c3ba02ddd43ee3a995e3
- [x] 2.2 175d3a575b23a72d926e493567f73dc69862cfd3
- [ ] 2.3.0 4c9e4b4e77dc052dc223d5a6c3eae539a9db7b30
  - (historical note: this is the release that replaced "-" with "no" in options: -detach became nodetach)
- [ ] 2.3.1 383401cdb046c2038cd2d45e9b1427c9c1f62238
- [ ] 2.3.2 09032f7c09a5ead7d5cd14a61d17d1d495bf80f5
- [ ] 2.3.3 7ecd94f94b5e81f5a4b15beaae1f917f0874bea6
- [ ] 2.3.4 4f5726f47b4c847ac16a8c04885c82f3f108e909
- [ ] 2.3.5 8ef130a49773ca93ddedf3bbd254e601c7d157b1
- [x] 2.3.6 788d3e17a1913bf65a0f558354a4d31b04b5be1d
- [x] 2.3.7 6d494c9322033d7460c233940ec41611cc9d5294
- [ ] 2.3.8 da085a7dca7340ae4d641c3fdf7af9ba2da9340f
- [ ] 2.3.9 2654c68dbaa33726d6dcdab6c32a0f293b8cdcea
- [ ] 2.3.10 5755b0122ae26624b5f8bab08851014ba5a4770d
- [ ] 2.0.4 3597696e95ef3ab2799020162b72bfaa4b83fe4e
- [ ] 2.3.11 fea937ca274527cce12ff493be219aa0c93f9d53
- [ ] 2.4.0 26703b215b0b68d7005e6b5e41d744101471a743
- [ ] 2.4.1 d53d8e8a31da10c5072ca4418f6f211e908d3d8c
- [ ] 2.4.2 889f464325b70b95ac3a54219158f2fce8f16741
- [ ] 2.4.3 ff9c589fef9957c502594d23be7f7fc3d8845161
- [x] 2.4.4 5315b04acb34569907c6441ce83b5081c9a29981
- [ ] 2.0.3 79e6517a798202917397da66a20201d725d2134f
- [ ] 2.4.5 da6956a56ea8550f33287fc86a960df8ce1b9af0
- [ ] 2.4.6 4043750fca36e7e0eb90d702e048ad1da4929418
- [x] 2.4.7 6e8eaa7a78b31cdab2edf140a9c8afdb02ffaca5

some of these are approximations of when the releases were made based on the commit messages.

**Comment by cognifloyd** [comment]
Sorry for posting this so soon. I hit enter one too many times. I'll update the list with the commits that need to be tagged.

**Comment by paulusmack** [comment]
I have pushed out tags for most of those releases, as many as I still have the .tar.gz (or .tar.Z) file for.
