### ISSUE TITLE
Busy loop for L2TP VPN's

### ISSUE THREAD

**Issue by duffolonious** [paulusmack/ppp#7]
I think this patch fixes the problem - exit when the file fails to open.

Otherwise it tries to open files that don't exist about a million times:
XXX XX 00:00:38 localhost pppd[29325]: Failed to open /dev/pts/1: No such file or directory

Until you restart it.

Fix:

```
diff --git a/pppd/tty.c b/pppd/tty.c
index d571b11..0fb8964 100644
--- a/pppd/tty.c
+++ b/pppd/tty.c
@@ -579,6 +579,7 @@ int connect_tty()
            if (err != EINTR) {
                error("Failed to open %s: %m", devnam);
                status = EXIT_OPEN_FAILED;
+               goto errret;
            }
            if (!persist || err != EINTR)
                goto errret;
```

**Comment by paulusmack** [comment]
closing due to lack of response to questions
