### ISSUE TITLE
Add systemd daemon support

### ISSUE THREAD

**Issue by cognifloyd** [paulusmack/ppp#70]
nodetach and updetach are helpful, but it is difficult for systemd to know when pppd is up enough to start services that depend on it. Explicit systemd support would make dependencies easier to deal with.

**Comment by gkarakou** [comment]
It would be great to add systemd support (and beyond sd_notify). Currently there is no way to execute pppd under an unprivileged linux account via systemd. Maybe some parts would have to be rewritten for seteuid,seteguid calls after pppoe discovery stage has been completed and routes have been added to run pppoe session stage under a limited account.
