### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by teknoraver** [paulusmack/ppp#71]
Please answer and close the bug if it's still maintained by someone.

**Comment by mysticall** [comment]
radattr.c not compatible with new FreeRADIUS Client Library. Maybe and radius.c not compatible.

**Comment by jidanni** [comment]
Well maybe we can send bug reports to https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=ppp .

**Comment by bootc** [comment]
Please don't send upstream bugs to Debian's ppp package. I may maintain the Debian package, but I do _not_ wish to become the ppp upstream, sorry.

**Comment by mysticall** [comment]
This problem must be fixed before the next stable Debian.

**Comment by yegorich** [comment]
ppp seems to be maintained by [samba.org](https://ppp.samba.org/index.html). This would be the right place to ask. Does anyone have a good contact there?
