### ISSUE TITLE
busy loop: received SIGTERM before auth fail

### ISSUE THREAD

**Issue by anyhit** [paulusmack/ppp#75]
ppp-2.4.7 xl2tpd-1.3.0： dial with a error password
logread：
daemon.err Feb 21 15:43:48 pppd[15495]: Failed to open /dev/pts/1: No such file or directory

code:
pppd/tty.c
 518 int connect_tty()
 519 {
……
            /*get sigterm and got_sigterm=SIGTERM*/
 561         got_sigterm = 0;/*got_sigterm be cleared,so SIGTERM lossed*/
……
 770         if (got_sigterm)
 771                 asked_to_quit = 1;/*got_sigterm == 0, don't quit,  and there is not a sleep so busy loop*/
 772         return -1;
 773 }

**Comment by paulusmack** [comment]
Is this still an issue with the current pppd source? If so, please provide step-by-step instructions to replicate the problem.
