### ISSUE TITLE
Add ipv6cp-accept-remote option

### ISSUE THREAD

**Issue by sthibaul** [paulusmack/ppp#76]
Hello,

The patch below comes from fedora & debian, it adds the ipv6cp-accept-remote option, which behaves like its v4 counterpart, ipcp-accept-remote.

[patch.txt](https://github.com/paulusmack/ppp/files/797825/patch.txt)

**Comment by Neustradamus** [comment]
@sthibaul: The code is always good for current master?

@paulusmack: Can you look?

**Comment by sthibaul** [comment]
It is still exactly like that in Debian 2.4.7, yes.

**Comment by Neustradamus** [comment]
@sthibaul: Maybe good to do a PR?

**Comment by Neustradamus** [comment]
@paulusmack: Any news?

**Comment by pali** [comment]
FYI, pull request: https://github.com/paulusmack/ppp/pull/145
