### ISSUE TITLE
pppd reconnecting when persist is off

### ISSUE THREAD

**Issue by ommos61** [paulusmack/ppp#8]
I have a situation in a mobile device where we do a border-crossing and the connection is terminated and trying to be restarted when the persist flag is off in the configuration.

The thing that happens is that the ppp peer sends a TermReq and the pppd shuts down the connection, sends the TermAck, but then tries to start it up again (running the connect script, etc).  This happens when the persist flag is set to off.

I have traced back the problem to what seems to be a missing 'if' condition in the FSM when fsm_lowerdown() is called for LCP when that FSM is in the STOPPED state. In that case the FSM state is unconditionally set to STARTING and the starting callbacks are run, which will cause the connection to be restarted.

My proposed fix for this would be to include an 'if' condition on the persist flag around the restarting code:

```
void
fsm_lowerdown(f)
    fsm *f;
{
    switch( f->state ){
...
    case STOPPED:
        if (persist) {
            f->state = STARTING;
            if( f->callbacks->starting )
                (*f->callbacks->starting)(f);
        }
    break;
...
```

**Comment by paulusmack** [comment]
closing due to lack of response
