### ISSUE TITLE
pptp host route issue

### ISSUE THREAD

**Issue by sparse91** [paulusmack/ppp#81]
Hi
pptp doesn't add host route entry in route table. It was working before.

Linux arch 4.10.10-1-ARCH x86_64
pptpclient 1.8.0-2

**Comment by Neustradamus** [comment]
@sparse91: Your problem has been solved?
Go here: https://github.com/quozl/pptp

**Comment by Neustradamus** [comment]
@sparse91: Your problem has been solved?

**Comment by sparse91** [comment]
It seems work now without problem.
Linux ARCH 5.8.13-arch1-1
pptpclient 1.10.0-2
