### ISSUE TITLE
Another pptp fail with VPN firewall

### ISSUE THREAD

**Issue by aaron-w2** [paulusmack/ppp#85]
I am seeing PPTP fail during lcp negotiation with a particular firewall. I believe the issue may be that ppp is neither acknowledging nor rejecting the configuration requests sent by the firewall.

In this case the server is sending callback, CBCP, BACP and a multilink endpoint discriminator parameters.

I have attached a GRE capture using wireshark

[pptp-fail2.pcapng.zip](https://github.com/paulusmack/ppp/files/1065800/pptp-fail2.pcapng.zip)

**Comment by paulusmack** [comment]
Again, use the debug option on your pppd to see what it is receiving. If pppd is not receiving the packets from the peer then the problem is not in pppd, it's in whatever is supposed to be delivering the packets to pppd.
