### ISSUE TITLE
Lost CHAP authentication packets do not result in a timeout by the client

### ISSUE THREAD

**Issue by nomis** [paulusmack/ppp#87]
If CHAP authentication is required with the peer but this is never completed (either because the server never sends the challenge or because the client doesn't receive the outcome) then the client will wait forever, relying on the server to terminate the connection.

This can easily happen if the CHAP challenge or outcome packet is lost for any reason.

**Comment by nomis** [comment]
Comments copied from my PR that fixes the issue but has been closed:

----

> Hmmm, when the timeout occurs, I think it would be better to resend the CHAP-Response packet, instead of just giving up.

The client can't send a `CHAP Response` if it never received a `CHAP Challenge`. The server may not resend this or the retries may also be lost, so the client must timeout in this scenario.

The server may not accept a duplicate `CHAP Response` a full 60 seconds later, especially when it has already sent a `CHAP Success`.  This would add an assumption about how the other side of the link will behave. It looks like `ppp` would do this, but RFC 1334 does not require it. Only PAP explicitly specifies that retries will occur indefinitely.

----

The server is also allowed to send multiple challenges, so the client may be retrying the response to an earlier challenge if there are two consecutive challenges and multiple lost packets.

In the UK the majority of DSL lines use BT Wholesale connections that perform the CHAP authentication using RADIUS and then hand-off to the PPP via L2TP to a remote server which then (usually) starts LCP again and does another CHAP authentication.

It's possible for the remote server to simply do a second `CHAP Challenge` (which is also lost). In that scenario the client would be retransmitting the wrong `CHAP Response` because the challenge value will be different.

It's possible for the remote server to start IPCP/IPV6CP without restarting LCP. In that scenario the client would be retransmitting the `CHAP Response` to a device that may not have the original challenge value and may not respond appropriately.

----

Here's a comment on the implementation used by [FireBrick](https://www.firebrick.co.uk/):
> The system handles failure of a chap packet at any stage quite well with the appropriate resend. A whole minute may be too long though.

**Comment by paulusmack** [comment]
Fixed by a72f809b1dfe.
