### ISSUE TITLE
Add support for IPv6 RADIUS attributes

### ISSUE THREAD

**Issue by santiagorr** [paulusmack/ppp#89]
Alarig Le Lay reported an issue about handling IPv6 radius attributes, and proposed a patch in [https://marc.info/?l=linux-ppp&m=145226335014356&w=2](https://marc.info/?l=linux-ppp&m=145226335014356&w=2)

The patch has been proposed to debian in 
[https://bugs.debian.org/874620](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874620#10 )
and I am just forwarding the patch here for making it more visible.
A patched ppp version is currently being used by grifon.fr ISP.

Cheers,
Santiago

**Comment by mysticall** [comment]
Alarig Le Lay patch:
[IPv6-attributes.txt](https://github.com/paulusmack/ppp/files/1347393/IPv6-attributes.txt)

[https://github.com/paulusmack/ppp/tree/master/pppd/plugins/radius](url)
[https://github.com/radcli/radcli/tree/master/lib](url)
There are major changes between the FreeRadius client in PPP and the current radcli.

**Comment by Neustradamus** [comment]
@santiagorr, @mysticall: In 2020, always good?
Can you look with the master branch?

@paulusmack: Can you look?

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by Neustradamus** [comment]
@alarig: It is possible to do a PR with your fix?

Informations by @santiagorr and @mysticall.

Thanks in advance.

**Comment by paulusmack** [comment]
#176 is now merged.
