### ISSUE TITLE
Use openssl instead of the libcrypt for DES (glibc dropped libcrypt)

### ISSUE THREAD

**Issue by yarda** [paulusmack/ppp#93]
Hi,

it seems the latest glibc (in Fedora glibc-2.27.9000-12.fc29) dropped libcrypt. The libxcrypt standalone package can be used instead, but it dropped the old setkey/encrypt API which ppp uses for DES. Thus the ppp should probably use openssl for the DES. I noticed there is already support for it in pppcrypt.c, but it seems unmaintained, contains typos preventing it from compilation and it seems to be written for ancient openssl version. I updated the code and tested with simple unit test on Fedora 29. Fedora bugzilla containing the patch and test:
https://bugzilla.redhat.com/show_bug.cgi?id=1556132

I could do pull request if needed.

**Comment by Neustradamus** [comment]
@yarda: Merged here: https://github.com/paulusmack/ppp/commit/3c7b86229f7bd2600d74db14b1fe5b3896be3875

Linked to:
- https://github.com/paulusmack/ppp/pull/96
