### ISSUE TITLE
incorrect pppd exit status in HTML man page

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [paulusmack/ppp#94]
The enumeration of exit statuses is not properly generated in the [HTML man page](https://ppp.samba.org/pppd.html#sect12):
> 1. Pppd has detached, or otherwise the connection was successfully established and terminated at the peer's request.
> 2. An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
> 3. An error was detected in processing the options given, such as two mutually exclusive options being used.
> 4. Pppd is not setuid-root and the invoking user is not root.

Compare to the [source](https://github.com/paulusmack/ppp/blob/a3f379b/pppd/pppd.8#L1522-L1595):
> ```
> .TP
> .B 0
> Pppd has detached, or otherwise the connection was successfully
> established and terminated at the peer's request.
> .TP
> .B 1
> An immediately fatal error of some kind occurred, such as an essential
> system call failing, or running out of virtual memory.
> .TP
> .B 2
> An error was detected in processing the options given, such as two
> mutually exclusive options being used.
> .TP
> .B 3
> Pppd is not setuid-root and the invoking user is not root.
> .TP
> .B 4
> The kernel does not support PPP, for example, the PPP kernel driver is
> not included or cannot be loaded.```

The numerical exit codes are shifted by one.

**Comment by paulusmack** [comment]
Now fixed.
